import type { EmojiData } from "./types";

/**
 * Auto-generated emoji data mapping.
 * Source: emoji-datasource (Unicode CLDR), validated against Noto Emoji
 * Generated: 2026-07-12
 * Count: 891 emojis
 *
 * To regenerate: npx tsx scripts/generate-emoji-data.ts
 * To add all emojis: npx tsx scripts/generate-emoji-data.ts --all
 * Quick (no validation): npx tsx scripts/generate-emoji-data.ts --quick
 */

export const emojiData: Record<string, EmojiData> = {
  // ─── Travel & Places (124) ───
  "🌀": { name: "cyclone_1f300", alt: "Cyclone", codepoint: "1f300" },
  "🌁": { name: "foggy_1f301", alt: "Foggy", codepoint: "1f301" },
  "🌂": { name: "closed-umbrella_1f302", alt: "Closed umbrella", codepoint: "1f302" },
  "🌃": { name: "night-with-stars_1f303", alt: "Night with stars", codepoint: "1f303" },
  "🌄": { name: "sunrise-over-mountains_1f304", alt: "Sunrise over mountains", codepoint: "1f304" },
  "🌅": { name: "sunrise_1f305", alt: "Sunrise", codepoint: "1f305" },
  "🌆": { name: "cityscape-at-dusk_1f306", alt: "Cityscape at dusk", codepoint: "1f306" },
  "🌈": { name: "rainbow_1f308", alt: "Rainbow", codepoint: "1f308" },
  "🌉": { name: "bridge-at-night_1f309", alt: "Bridge at night", codepoint: "1f309" },
  "🌊": { name: "water-wave_1f30a", alt: "Water wave", codepoint: "1f30a" },
  "🌋": { name: "volcano_1f30b", alt: "Volcano", codepoint: "1f30b" },
  "🌌": { name: "milky-way_1f30c", alt: "Milky way", codepoint: "1f30c" },
  "🌐": { name: "globe-with-meridians_1f310", alt: "Globe with meridians", codepoint: "1f310" },
  "🌑": { name: "new-moon_1f311", alt: "New moon symbol", codepoint: "1f311" },
  "🌒": { name: "waxing-crescent-moon_1f312", alt: "Waxing crescent moon symbol", codepoint: "1f312" },
  "🌓": { name: "first-quarter-moon_1f313", alt: "First quarter moon symbol", codepoint: "1f313" },
  "🌔": { name: "waxing-gibbous-moon_1f314", alt: "Waxing gibbous moon symbol", codepoint: "1f314" },
  "🌕": { name: "full-moon_1f315", alt: "Full moon symbol", codepoint: "1f315" },
  "🌖": { name: "waning-gibbous-moon_1f316", alt: "Waning gibbous moon symbol", codepoint: "1f316" },
  "🌗": { name: "last-quarter-moon_1f317", alt: "Last quarter moon symbol", codepoint: "1f317" },
  "🌘": { name: "waning-crescent-moon_1f318", alt: "Waning crescent moon symbol", codepoint: "1f318" },
  "🌙": { name: "crescent-moon_1f319", alt: "Crescent moon", codepoint: "1f319" },
  "🌞": { name: "sun-with-face_1f31e", alt: "Sun with face", codepoint: "1f31e" },
  "🌟": { name: "glowing-star_1f31f", alt: "Glowing star", codepoint: "1f31f" },
  "🌠": { name: "shooting-star_1f320", alt: "Shooting star", codepoint: "1f320" },
  "🎠": { name: "carousel-horse_1f3a0", alt: "Carousel horse", codepoint: "1f3a0" },
  "🎡": { name: "ferris-wheel_1f3a1", alt: "Ferris wheel", codepoint: "1f3a1" },
  "🎢": { name: "roller-coaster_1f3a2", alt: "Roller coaster", codepoint: "1f3a2" },
  "🎪": { name: "circus-tent_1f3aa", alt: "Circus tent", codepoint: "1f3aa" },
  "🏠": { name: "house_1f3e0", alt: "House building", codepoint: "1f3e0" },
  "🏡": { name: "house-with-garden_1f3e1", alt: "House with garden", codepoint: "1f3e1" },
  "🏢": { name: "office-building_1f3e2", alt: "Office building", codepoint: "1f3e2" },
  "🏣": { name: "japanese-post-office_1f3e3", alt: "Japanese post office", codepoint: "1f3e3" },
  "🏥": { name: "hospital_1f3e5", alt: "Hospital", codepoint: "1f3e5" },
  "🏦": { name: "bank_1f3e6", alt: "Bank", codepoint: "1f3e6" },
  "🏨": { name: "hotel_1f3e8", alt: "Hotel", codepoint: "1f3e8" },
  "🏩": { name: "love-hotel_1f3e9", alt: "Love hotel", codepoint: "1f3e9" },
  "🏪": { name: "convenience-store_1f3ea", alt: "Convenience store", codepoint: "1f3ea" },
  "🏫": { name: "school_1f3eb", alt: "School", codepoint: "1f3eb" },
  "🏬": { name: "department-store_1f3ec", alt: "Department store", codepoint: "1f3ec" },
  "🏭": { name: "factory_1f3ed", alt: "Factory", codepoint: "1f3ed" },
  "🏯": { name: "japanese-castle_1f3ef", alt: "Japanese castle", codepoint: "1f3ef" },
  "💈": { name: "barber-pole_1f488", alt: "Barber pole", codepoint: "1f488" },
  "💒": { name: "wedding_1f492", alt: "Wedding", codepoint: "1f492" },
  "💧": { name: "droplet_1f4a7", alt: "Droplet", codepoint: "1f4a7" },
  "💺": { name: "seat_1f4ba", alt: "Seat", codepoint: "1f4ba" },
  "🔥": { name: "fire_1f525", alt: "Fire", codepoint: "1f525" },
  "🕋": { name: "kaaba_1f54b", alt: "Kaaba", codepoint: "1f54b" },
  "🕌": { name: "mosque_1f54c", alt: "Mosque", codepoint: "1f54c" },
  "🕍": { name: "synagogue_1f54d", alt: "Synagogue", codepoint: "1f54d" },
  "🗻": { name: "mount-fuji_1f5fb", alt: "Mount fuji", codepoint: "1f5fb" },
  "🗼": { name: "tokyo-tower_1f5fc", alt: "Tokyo tower", codepoint: "1f5fc" },
  "🗽": { name: "statue-of-liberty_1f5fd", alt: "Statue of liberty", codepoint: "1f5fd" },
  "🚀": { name: "rocket_1f680", alt: "Rocket", codepoint: "1f680" },
  "🚁": { name: "helicopter_1f681", alt: "Helicopter", codepoint: "1f681" },
  "🚃": { name: "railway-car_1f683", alt: "Railway car", codepoint: "1f683" },
  "🚄": { name: "high-speed-train_1f684", alt: "High-speed train", codepoint: "1f684" },
  "🚆": { name: "train_1f686", alt: "Train", codepoint: "1f686" },
  "🚇": { name: "metro_1f687", alt: "Metro", codepoint: "1f687" },
  "🚈": { name: "light-rail_1f688", alt: "Light rail", codepoint: "1f688" },
  "🚉": { name: "station_1f689", alt: "Station", codepoint: "1f689" },
  "🚊": { name: "tram_1f68a", alt: "Tram", codepoint: "1f68a" },
  "🚋": { name: "tram-car_1f68b", alt: "Tram car", codepoint: "1f68b" },
  "🚌": { name: "bus_1f68c", alt: "Bus", codepoint: "1f68c" },
  "🚍": { name: "oncoming-bus_1f68d", alt: "Oncoming bus", codepoint: "1f68d" },
  "🚎": { name: "trolleybus_1f68e", alt: "Trolleybus", codepoint: "1f68e" },
  "🚏": { name: "bus-stop_1f68f", alt: "Bus stop", codepoint: "1f68f" },
  "🚐": { name: "minibus_1f690", alt: "Minibus", codepoint: "1f690" },
  "🚑": { name: "ambulance_1f691", alt: "Ambulance", codepoint: "1f691" },
  "🚒": { name: "fire-engine_1f692", alt: "Fire engine", codepoint: "1f692" },
  "🚓": { name: "police-car_1f693", alt: "Police car", codepoint: "1f693" },
  "🚔": { name: "oncoming-police-car_1f694", alt: "Oncoming police car", codepoint: "1f694" },
  "🚕": { name: "taxi_1f695", alt: "Taxi", codepoint: "1f695" },
  "🚖": { name: "oncoming-taxi_1f696", alt: "Oncoming taxi", codepoint: "1f696" },
  "🚗": { name: "automobile_1f697", alt: "Automobile", codepoint: "1f697" },
  "🚘": { name: "oncoming-automobile_1f698", alt: "Oncoming automobile", codepoint: "1f698" },
  "🚚": { name: "delivery-truck_1f69a", alt: "Delivery truck", codepoint: "1f69a" },
  "🚛": { name: "articulated-lorry_1f69b", alt: "Articulated lorry", codepoint: "1f69b" },
  "🚜": { name: "tractor_1f69c", alt: "Tractor", codepoint: "1f69c" },
  "🚝": { name: "monorail_1f69d", alt: "Monorail", codepoint: "1f69d" },
  "🚞": { name: "mountain-railway_1f69e", alt: "Mountain railway", codepoint: "1f69e" },
  "🚟": { name: "suspension-railway_1f69f", alt: "Suspension railway", codepoint: "1f69f" },
  "🚠": { name: "mountain-cableway_1f6a0", alt: "Mountain cableway", codepoint: "1f6a0" },
  "🚡": { name: "aerial-tramway_1f6a1", alt: "Aerial tramway", codepoint: "1f6a1" },
  "🚢": { name: "ship_1f6a2", alt: "Ship", codepoint: "1f6a2" },
  "🚤": { name: "speedboat_1f6a4", alt: "Speedboat", codepoint: "1f6a4" },
  "🚥": { name: "horizontal-traffic-light_1f6a5", alt: "Horizontal traffic light", codepoint: "1f6a5" },
  "🚦": { name: "vertical-traffic-light_1f6a6", alt: "Vertical traffic light", codepoint: "1f6a6" },
  "🚧": { name: "construction_1f6a7", alt: "Construction sign", codepoint: "1f6a7" },
  "🚲": { name: "bicycle_1f6b2", alt: "Bicycle", codepoint: "1f6b2" },
  "🛕": { name: "hindu-temple_1f6d5", alt: "Hindu temple", codepoint: "1f6d5" },
  "🛖": { name: "hut_1f6d6", alt: "Hut", codepoint: "1f6d6" },
  "🛝": { name: "playground-slide_1f6dd", alt: "Playground slide", codepoint: "1f6dd" },
  "🛞": { name: "wheel_1f6de", alt: "Wheel", codepoint: "1f6de" },
  "🛟": { name: "ring-buoy_1f6df", alt: "Ring buoy", codepoint: "1f6df" },
  "🛫": { name: "airplane-departure_1f6eb", alt: "Airplane departure", codepoint: "1f6eb" },
  "🛵": { name: "motor-scooter_1f6f5", alt: "Motor scooter", codepoint: "1f6f5" },
  "🛶": { name: "canoe_1f6f6", alt: "Canoe", codepoint: "1f6f6" },
  "🛸": { name: "flying-saucer_1f6f8", alt: "Flying saucer", codepoint: "1f6f8" },
  "🛹": { name: "skateboard_1f6f9", alt: "Skateboard", codepoint: "1f6f9" },
  "🛺": { name: "auto-rickshaw_1f6fa", alt: "Auto rickshaw", codepoint: "1f6fa" },
  "🛻": { name: "pickup-truck_1f6fb", alt: "Pickup truck", codepoint: "1f6fb" },
  "🛼": { name: "roller-skate_1f6fc", alt: "Roller skate", codepoint: "1f6fc" },
  "🦼": { name: "motorized-wheelchair_1f9bc", alt: "Motorized wheelchair", codepoint: "1f9bc" },
  "🦽": { name: "manual-wheelchair_1f9bd", alt: "Manual wheelchair", codepoint: "1f9bd" },
  "🧭": { name: "compass_1f9ed", alt: "Compass", codepoint: "1f9ed" },
  "🧱": { name: "brick_1f9f1", alt: "Brick", codepoint: "1f9f1" },
  "🧳": { name: "luggage_1f9f3", alt: "Luggage", codepoint: "1f9f3" },
  "🪂": { name: "parachute_1fa82", alt: "Parachute", codepoint: "1fa82" },
  "🪐": { name: "ringed-planet_1fa90", alt: "Ringed planet", codepoint: "1fa90" },
  "🪨": { name: "rock_1faa8", alt: "Rock", codepoint: "1faa8" },
  "🪵": { name: "wood_1fab5", alt: "Wood", codepoint: "1fab5" },
  "⌚": { name: "watch_231a", alt: "Watch", codepoint: "231a" },
  "⏰": { name: "alarm-clock_23f0", alt: "Alarm clock", codepoint: "23f0" },
  "☔": { name: "umbrella-with-rain-drops_2614", alt: "Umbrella with rain drops", codepoint: "2614" },
  "⚓": { name: "anchor_2693", alt: "Anchor", codepoint: "2693" },
  "⛄": { name: "snowman-without-snow_26c4", alt: "Snowman without snow", codepoint: "26c4" },
  "⛅": { name: "sun-behind-cloud_26c5", alt: "Sun behind cloud", codepoint: "26c5" },
  "⛪": { name: "church_26ea", alt: "Church", codepoint: "26ea" },
  "⛲": { name: "fountain_26f2", alt: "Fountain", codepoint: "26f2" },
  "⛵": { name: "sailboat_26f5", alt: "Sailboat", codepoint: "26f5" },
  "⛺": { name: "tent_26fa", alt: "Tent", codepoint: "26fa" },
  "⛽": { name: "fuel-pump_26fd", alt: "Fuel pump", codepoint: "26fd" },
  "⭐": { name: "star_2b50", alt: "White medium star", codepoint: "2b50" },

  // ─── Food & Drink (123) ───
  "🌭": { name: "hot-dog_1f32d", alt: "Hot dog", codepoint: "1f32d" },
  "🌮": { name: "taco_1f32e", alt: "Taco", codepoint: "1f32e" },
  "🌯": { name: "burrito_1f32f", alt: "Burrito", codepoint: "1f32f" },
  "🌰": { name: "chestnut_1f330", alt: "Chestnut", codepoint: "1f330" },
  "🍅": { name: "tomato_1f345", alt: "Tomato", codepoint: "1f345" },
  "🍆": { name: "eggplant_1f346", alt: "Aubergine", codepoint: "1f346" },
  "🍇": { name: "grapes_1f347", alt: "Grapes", codepoint: "1f347" },
  "🍈": { name: "melon_1f348", alt: "Melon", codepoint: "1f348" },
  "🍉": { name: "watermelon_1f349", alt: "Watermelon", codepoint: "1f349" },
  "🍊": { name: "tangerine_1f34a", alt: "Tangerine", codepoint: "1f34a" },
  "🍋": { name: "lemon_1f34b", alt: "Lemon", codepoint: "1f34b" },
  "🍌": { name: "banana_1f34c", alt: "Banana", codepoint: "1f34c" },
  "🍍": { name: "pineapple_1f34d", alt: "Pineapple", codepoint: "1f34d" },
  "🍎": { name: "red-apple_1f34e", alt: "Red apple", codepoint: "1f34e" },
  "🍏": { name: "green-apple_1f34f", alt: "Green apple", codepoint: "1f34f" },
  "🍐": { name: "pear_1f350", alt: "Pear", codepoint: "1f350" },
  "🍑": { name: "peach_1f351", alt: "Peach", codepoint: "1f351" },
  "🍒": { name: "cherries_1f352", alt: "Cherries", codepoint: "1f352" },
  "🍓": { name: "strawberry_1f353", alt: "Strawberry", codepoint: "1f353" },
  "🍔": { name: "hamburger_1f354", alt: "Hamburger", codepoint: "1f354" },
  "🍕": { name: "pizza_1f355", alt: "Slice of pizza", codepoint: "1f355" },
  "🍖": { name: "meat-on-bone_1f356", alt: "Meat on bone", codepoint: "1f356" },
  "🍗": { name: "poultry-leg_1f357", alt: "Poultry leg", codepoint: "1f357" },
  "🍘": { name: "rice-cracker_1f358", alt: "Rice cracker", codepoint: "1f358" },
  "🍙": { name: "rice-ball_1f359", alt: "Rice ball", codepoint: "1f359" },
  "🍚": { name: "cooked-rice_1f35a", alt: "Cooked rice", codepoint: "1f35a" },
  "🍜": { name: "steaming-bowl_1f35c", alt: "Steaming bowl", codepoint: "1f35c" },
  "🍝": { name: "spaghetti_1f35d", alt: "Spaghetti", codepoint: "1f35d" },
  "🍞": { name: "bread_1f35e", alt: "Bread", codepoint: "1f35e" },
  "🍟": { name: "french-fries_1f35f", alt: "French fries", codepoint: "1f35f" },
  "🍠": { name: "roasted-sweet-potato_1f360", alt: "Roasted sweet potato", codepoint: "1f360" },
  "🍡": { name: "dango_1f361", alt: "Dango", codepoint: "1f361" },
  "🍢": { name: "oden_1f362", alt: "Oden", codepoint: "1f362" },
  "🍣": { name: "sushi_1f363", alt: "Sushi", codepoint: "1f363" },
  "🍤": { name: "fried-shrimp_1f364", alt: "Fried shrimp", codepoint: "1f364" },
  "🍦": { name: "soft-ice-cream_1f366", alt: "Soft ice cream", codepoint: "1f366" },
  "🍧": { name: "shaved-ice_1f367", alt: "Shaved ice", codepoint: "1f367" },
  "🍨": { name: "ice-cream_1f368", alt: "Ice cream", codepoint: "1f368" },
  "🍩": { name: "doughnut_1f369", alt: "Doughnut", codepoint: "1f369" },
  "🍪": { name: "cookie_1f36a", alt: "Cookie", codepoint: "1f36a" },
  "🍫": { name: "chocolate-bar_1f36b", alt: "Chocolate bar", codepoint: "1f36b" },
  "🍬": { name: "candy_1f36c", alt: "Candy", codepoint: "1f36c" },
  "🍭": { name: "lollipop_1f36d", alt: "Lollipop", codepoint: "1f36d" },
  "🍮": { name: "custard_1f36e", alt: "Custard", codepoint: "1f36e" },
  "🍯": { name: "honey-pot_1f36f", alt: "Honey pot", codepoint: "1f36f" },
  "🍰": { name: "shortcake_1f370", alt: "Shortcake", codepoint: "1f370" },
  "🍱": { name: "bento-box_1f371", alt: "Bento box", codepoint: "1f371" },
  "🍲": { name: "pot-of-food_1f372", alt: "Pot of food", codepoint: "1f372" },
  "🍳": { name: "cooking_1f373", alt: "Cooking", codepoint: "1f373" },
  "🍴": { name: "fork-and-knife_1f374", alt: "Fork and knife", codepoint: "1f374" },
  "🍵": { name: "teacup-without-handle_1f375", alt: "Teacup without handle", codepoint: "1f375" },
  "🍶": { name: "sake_1f376", alt: "Sake bottle and cup", codepoint: "1f376" },
  "🍷": { name: "wine-glass_1f377", alt: "Wine glass", codepoint: "1f377" },
  "🍸": { name: "cocktail-glass_1f378", alt: "Cocktail glass", codepoint: "1f378" },
  "🍹": { name: "tropical-drink_1f379", alt: "Tropical drink", codepoint: "1f379" },
  "🍺": { name: "beer-mug_1f37a", alt: "Beer mug", codepoint: "1f37a" },
  "🍻": { name: "clinking-beer-mugs_1f37b", alt: "Clinking beer mugs", codepoint: "1f37b" },
  "🍼": { name: "baby-bottle_1f37c", alt: "Baby bottle", codepoint: "1f37c" },
  "🍾": { name: "bottle-with-popping-cork_1f37e", alt: "Bottle with popping cork", codepoint: "1f37e" },
  "🍿": { name: "popcorn_1f37f", alt: "Popcorn", codepoint: "1f37f" },
  "🎂": { name: "birthday-cake_1f382", alt: "Birthday cake", codepoint: "1f382" },
  "🏺": { name: "amphora_1f3fa", alt: "Amphora", codepoint: "1f3fa" },
  "🥂": { name: "clinking-glasses_1f942", alt: "Clinking glasses", codepoint: "1f942" },
  "🥃": { name: "tumbler-glass_1f943", alt: "Tumbler glass", codepoint: "1f943" },
  "🥄": { name: "spoon_1f944", alt: "Spoon", codepoint: "1f944" },
  "🥐": { name: "croissant_1f950", alt: "Croissant", codepoint: "1f950" },
  "🥑": { name: "avocado_1f951", alt: "Avocado", codepoint: "1f951" },
  "🥒": { name: "cucumber_1f952", alt: "Cucumber", codepoint: "1f952" },
  "🥓": { name: "bacon_1f953", alt: "Bacon", codepoint: "1f953" },
  "🥔": { name: "potato_1f954", alt: "Potato", codepoint: "1f954" },
  "🥕": { name: "carrot_1f955", alt: "Carrot", codepoint: "1f955" },
  "🥖": { name: "baguette-bread_1f956", alt: "Baguette bread", codepoint: "1f956" },
  "🥗": { name: "green-salad_1f957", alt: "Green salad", codepoint: "1f957" },
  "🥘": { name: "shallow-pan-of-food_1f958", alt: "Shallow pan of food", codepoint: "1f958" },
  "🥙": { name: "stuffed-flatbread_1f959", alt: "Stuffed flatbread", codepoint: "1f959" },
  "🥚": { name: "egg_1f95a", alt: "Egg", codepoint: "1f95a" },
  "🥛": { name: "glass-of-milk_1f95b", alt: "Glass of milk", codepoint: "1f95b" },
  "🥜": { name: "peanuts_1f95c", alt: "Peanuts", codepoint: "1f95c" },
  "🥞": { name: "pancakes_1f95e", alt: "Pancakes", codepoint: "1f95e" },
  "🥟": { name: "dumpling_1f95f", alt: "Dumpling", codepoint: "1f95f" },
  "🥠": { name: "fortune-cookie_1f960", alt: "Fortune cookie", codepoint: "1f960" },
  "🥡": { name: "takeout-box_1f961", alt: "Takeout box", codepoint: "1f961" },
  "🥢": { name: "chopsticks_1f962", alt: "Chopsticks", codepoint: "1f962" },
  "🥣": { name: "bowl-with-spoon_1f963", alt: "Bowl with spoon", codepoint: "1f963" },
  "🥤": { name: "cup-with-straw_1f964", alt: "Cup with straw", codepoint: "1f964" },
  "🥥": { name: "coconut_1f965", alt: "Coconut", codepoint: "1f965" },
  "🥦": { name: "broccoli_1f966", alt: "Broccoli", codepoint: "1f966" },
  "🥧": { name: "pie_1f967", alt: "Pie", codepoint: "1f967" },
  "🥨": { name: "pretzel_1f968", alt: "Pretzel", codepoint: "1f968" },
  "🥩": { name: "cut-of-meat_1f969", alt: "Cut of meat", codepoint: "1f969" },
  "🥪": { name: "sandwich_1f96a", alt: "Sandwich", codepoint: "1f96a" },
  "🥫": { name: "canned-food_1f96b", alt: "Canned food", codepoint: "1f96b" },
  "🥬": { name: "leafy-green_1f96c", alt: "Leafy green", codepoint: "1f96c" },
  "🥭": { name: "mango_1f96d", alt: "Mango", codepoint: "1f96d" },
  "🥮": { name: "moon-cake_1f96e", alt: "Moon cake", codepoint: "1f96e" },
  "🥯": { name: "bagel_1f96f", alt: "Bagel", codepoint: "1f96f" },
  "🦀": { name: "crab_1f980", alt: "Crab", codepoint: "1f980" },
  "🦐": { name: "shrimp_1f990", alt: "Shrimp", codepoint: "1f990" },
  "🦑": { name: "squid_1f991", alt: "Squid", codepoint: "1f991" },
  "🦞": { name: "lobster_1f99e", alt: "Lobster", codepoint: "1f99e" },
  "🦪": { name: "oyster_1f9aa", alt: "Oyster", codepoint: "1f9aa" },
  "🧀": { name: "cheese-wedge_1f9c0", alt: "Cheese wedge", codepoint: "1f9c0" },
  "🧁": { name: "cupcake_1f9c1", alt: "Cupcake", codepoint: "1f9c1" },
  "🧂": { name: "salt_1f9c2", alt: "Salt shaker", codepoint: "1f9c2" },
  "🧃": { name: "beverage-box_1f9c3", alt: "Beverage box", codepoint: "1f9c3" },
  "🧄": { name: "garlic_1f9c4", alt: "Garlic", codepoint: "1f9c4" },
  "🧅": { name: "onion_1f9c5", alt: "Onion", codepoint: "1f9c5" },
  "🧆": { name: "falafel_1f9c6", alt: "Falafel", codepoint: "1f9c6" },
  "🧇": { name: "waffle_1f9c7", alt: "Waffle", codepoint: "1f9c7" },
  "🧈": { name: "butter_1f9c8", alt: "Butter", codepoint: "1f9c8" },
  "🧋": { name: "bubble-tea_1f9cb", alt: "Bubble tea", codepoint: "1f9cb" },
  "🫐": { name: "blueberries_1fad0", alt: "Blueberries", codepoint: "1fad0" },
  "🫑": { name: "bell-pepper_1fad1", alt: "Bell pepper", codepoint: "1fad1" },
  "🫒": { name: "olive_1fad2", alt: "Olive", codepoint: "1fad2" },
  "🫓": { name: "flatbread_1fad3", alt: "Flatbread", codepoint: "1fad3" },
  "🫔": { name: "tamale_1fad4", alt: "Tamale", codepoint: "1fad4" },
  "🫕": { name: "fondue_1fad5", alt: "Fondue", codepoint: "1fad5" },
  "🫖": { name: "teapot_1fad6", alt: "Teapot", codepoint: "1fad6" },
  "🫗": { name: "pouring-liquid_1fad7", alt: "Pouring liquid", codepoint: "1fad7" },
  "🫘": { name: "beans_1fad8", alt: "Beans", codepoint: "1fad8" },
  "🫙": { name: "jar_1fad9", alt: "Jar", codepoint: "1fad9" },
  "🫛": { name: "pea-pod_1fadb", alt: "Pea pod", codepoint: "1fadb" },
  "☕": { name: "hot-beverage_2615", alt: "Hot beverage", codepoint: "2615" },

  // ─── Animals & Nature (131) ───
  "🌱": { name: "seedling_1f331", alt: "Seedling", codepoint: "1f331" },
  "🌲": { name: "evergreen-tree_1f332", alt: "Evergreen tree", codepoint: "1f332" },
  "🌳": { name: "deciduous-tree_1f333", alt: "Deciduous tree", codepoint: "1f333" },
  "🌴": { name: "palm-tree_1f334", alt: "Palm tree", codepoint: "1f334" },
  "🌵": { name: "cactus_1f335", alt: "Cactus", codepoint: "1f335" },
  "🌷": { name: "tulip_1f337", alt: "Tulip", codepoint: "1f337" },
  "🌸": { name: "cherry-blossom_1f338", alt: "Cherry blossom", codepoint: "1f338" },
  "🌹": { name: "rose_1f339", alt: "Rose", codepoint: "1f339" },
  "🌺": { name: "hibiscus_1f33a", alt: "Hibiscus", codepoint: "1f33a" },
  "🌻": { name: "sunflower_1f33b", alt: "Sunflower", codepoint: "1f33b" },
  "🌼": { name: "blossom_1f33c", alt: "Blossom", codepoint: "1f33c" },
  "🌿": { name: "herb_1f33f", alt: "Herb", codepoint: "1f33f" },
  "🍀": { name: "four-leaf-clover_1f340", alt: "Four leaf clover", codepoint: "1f340" },
  "🍁": { name: "maple-leaf_1f341", alt: "Maple leaf", codepoint: "1f341" },
  "🍂": { name: "fallen-leaf_1f342", alt: "Fallen leaf", codepoint: "1f342" },
  "🍄": { name: "mushroom_1f344", alt: "Mushroom", codepoint: "1f344" },
  "🐀": { name: "rat_1f400", alt: "Rat", codepoint: "1f400" },
  "🐁": { name: "mouse_1f401", alt: "Mouse", codepoint: "1f401" },
  "🐂": { name: "ox_1f402", alt: "Ox", codepoint: "1f402" },
  "🐃": { name: "water-buffalo_1f403", alt: "Water buffalo", codepoint: "1f403" },
  "🐄": { name: "cow_1f404", alt: "Cow", codepoint: "1f404" },
  "🐅": { name: "tiger_1f405", alt: "Tiger", codepoint: "1f405" },
  "🐆": { name: "leopard_1f406", alt: "Leopard", codepoint: "1f406" },
  "🐇": { name: "rabbit_1f407", alt: "Rabbit", codepoint: "1f407" },
  "🐈": { name: "cat_1f408", alt: "Cat", codepoint: "1f408" },
  "🐉": { name: "dragon_1f409", alt: "Dragon", codepoint: "1f409" },
  "🐊": { name: "crocodile_1f40a", alt: "Crocodile", codepoint: "1f40a" },
  "🐋": { name: "whale_1f40b", alt: "Whale", codepoint: "1f40b" },
  "🐌": { name: "snail_1f40c", alt: "Snail", codepoint: "1f40c" },
  "🐍": { name: "snake_1f40d", alt: "Snake", codepoint: "1f40d" },
  "🐎": { name: "horse_1f40e", alt: "Horse", codepoint: "1f40e" },
  "🐏": { name: "ram_1f40f", alt: "Ram", codepoint: "1f40f" },
  "🐐": { name: "goat_1f410", alt: "Goat", codepoint: "1f410" },
  "🐒": { name: "monkey_1f412", alt: "Monkey", codepoint: "1f412" },
  "🐓": { name: "rooster_1f413", alt: "Rooster", codepoint: "1f413" },
  "🐔": { name: "chicken_1f414", alt: "Chicken", codepoint: "1f414" },
  "🐕": { name: "dog_1f415", alt: "Dog", codepoint: "1f415" },
  "🐖": { name: "pig_1f416", alt: "Pig", codepoint: "1f416" },
  "🐗": { name: "boar_1f417", alt: "Boar", codepoint: "1f417" },
  "🐘": { name: "elephant_1f418", alt: "Elephant", codepoint: "1f418" },
  "🐙": { name: "octopus_1f419", alt: "Octopus", codepoint: "1f419" },
  "🐚": { name: "spiral-shell_1f41a", alt: "Spiral shell", codepoint: "1f41a" },
  "🐛": { name: "bug_1f41b", alt: "Bug", codepoint: "1f41b" },
  "🐜": { name: "ant_1f41c", alt: "Ant", codepoint: "1f41c" },
  "🐝": { name: "honeybee_1f41d", alt: "Honeybee", codepoint: "1f41d" },
  "🐞": { name: "lady-beetle_1f41e", alt: "Lady beetle", codepoint: "1f41e" },
  "🐟": { name: "fish_1f41f", alt: "Fish", codepoint: "1f41f" },
  "🐠": { name: "tropical-fish_1f420", alt: "Tropical fish", codepoint: "1f420" },
  "🐡": { name: "blowfish_1f421", alt: "Blowfish", codepoint: "1f421" },
  "🐢": { name: "turtle_1f422", alt: "Turtle", codepoint: "1f422" },
  "🐣": { name: "hatching-chick_1f423", alt: "Hatching chick", codepoint: "1f423" },
  "🐤": { name: "baby-chick_1f424", alt: "Baby chick", codepoint: "1f424" },
  "🐥": { name: "front-facing-baby-chick_1f425", alt: "Front-facing baby chick", codepoint: "1f425" },
  "🐦": { name: "bird_1f426", alt: "Bird", codepoint: "1f426" },
  "🐧": { name: "penguin_1f427", alt: "Penguin", codepoint: "1f427" },
  "🐨": { name: "koala_1f428", alt: "Koala", codepoint: "1f428" },
  "🐩": { name: "poodle_1f429", alt: "Poodle", codepoint: "1f429" },
  "🐬": { name: "dolphin_1f42c", alt: "Dolphin", codepoint: "1f42c" },
  "🐭": { name: "mouse-face_1f42d", alt: "Mouse face", codepoint: "1f42d" },
  "🐮": { name: "cow-face_1f42e", alt: "Cow face", codepoint: "1f42e" },
  "🐯": { name: "tiger-face_1f42f", alt: "Tiger face", codepoint: "1f42f" },
  "🐰": { name: "rabbit-face_1f430", alt: "Rabbit face", codepoint: "1f430" },
  "🐱": { name: "cat-face_1f431", alt: "Cat face", codepoint: "1f431" },
  "🐲": { name: "dragon-face_1f432", alt: "Dragon face", codepoint: "1f432" },
  "🐳": { name: "spouting-whale_1f433", alt: "Spouting whale", codepoint: "1f433" },
  "🐴": { name: "horse-face_1f434", alt: "Horse face", codepoint: "1f434" },
  "🐵": { name: "monkey-face_1f435", alt: "Monkey face", codepoint: "1f435" },
  "🐶": { name: "dog-face_1f436", alt: "Dog face", codepoint: "1f436" },
  "🐷": { name: "pig-face_1f437", alt: "Pig face", codepoint: "1f437" },
  "🐸": { name: "frog_1f438", alt: "Frog face", codepoint: "1f438" },
  "🐹": { name: "hamster_1f439", alt: "Hamster face", codepoint: "1f439" },
  "🐺": { name: "wolf_1f43a", alt: "Wolf face", codepoint: "1f43a" },
  "🐻": { name: "bear_1f43b", alt: "Bear face", codepoint: "1f43b" },
  "🐽": { name: "pig-nose_1f43d", alt: "Pig nose", codepoint: "1f43d" },
  "🐾": { name: "paw-prints_1f43e", alt: "Paw prints", codepoint: "1f43e" },
  "💐": { name: "bouquet_1f490", alt: "Bouquet", codepoint: "1f490" },
  "💮": { name: "white-flower_1f4ae", alt: "White flower", codepoint: "1f4ae" },
  "🥀": { name: "wilted-flower_1f940", alt: "Wilted flower", codepoint: "1f940" },
  "🦂": { name: "scorpion_1f982", alt: "Scorpion", codepoint: "1f982" },
  "🦃": { name: "turkey_1f983", alt: "Turkey", codepoint: "1f983" },
  "🦅": { name: "eagle_1f985", alt: "Eagle", codepoint: "1f985" },
  "🦆": { name: "duck_1f986", alt: "Duck", codepoint: "1f986" },
  "🦇": { name: "bat_1f987", alt: "Bat", codepoint: "1f987" },
  "🦈": { name: "shark_1f988", alt: "Shark", codepoint: "1f988" },
  "🦉": { name: "owl_1f989", alt: "Owl", codepoint: "1f989" },
  "🦋": { name: "butterfly_1f98b", alt: "Butterfly", codepoint: "1f98b" },
  "🦌": { name: "deer_1f98c", alt: "Deer", codepoint: "1f98c" },
  "🦍": { name: "gorilla_1f98d", alt: "Gorilla", codepoint: "1f98d" },
  "🦎": { name: "lizard_1f98e", alt: "Lizard", codepoint: "1f98e" },
  "🦏": { name: "rhinoceros_1f98f", alt: "Rhinoceros", codepoint: "1f98f" },
  "🦔": { name: "hedgehog_1f994", alt: "Hedgehog", codepoint: "1f994" },
  "🦕": { name: "sauropod_1f995", alt: "Sauropod", codepoint: "1f995" },
  "🦖": { name: "t-rex_1f996", alt: "T-rex", codepoint: "1f996" },
  "🦗": { name: "cricket_1f997", alt: "Cricket", codepoint: "1f997" },
  "🦘": { name: "kangaroo_1f998", alt: "Kangaroo", codepoint: "1f998" },
  "🦙": { name: "llama_1f999", alt: "Llama", codepoint: "1f999" },
  "🦚": { name: "peacock_1f99a", alt: "Peacock", codepoint: "1f99a" },
  "🦛": { name: "hippopotamus_1f99b", alt: "Hippopotamus", codepoint: "1f99b" },
  "🦜": { name: "parrot_1f99c", alt: "Parrot", codepoint: "1f99c" },
  "🦝": { name: "raccoon_1f99d", alt: "Raccoon", codepoint: "1f99d" },
  "🦟": { name: "mosquito_1f99f", alt: "Mosquito", codepoint: "1f99f" },
  "🦠": { name: "microbe_1f9a0", alt: "Microbe", codepoint: "1f9a0" },
  "🦡": { name: "badger_1f9a1", alt: "Badger", codepoint: "1f9a1" },
  "🦢": { name: "swan_1f9a2", alt: "Swan", codepoint: "1f9a2" },
  "🦣": { name: "mammoth_1f9a3", alt: "Mammoth", codepoint: "1f9a3" },
  "🦤": { name: "dodo_1f9a4", alt: "Dodo", codepoint: "1f9a4" },
  "🦥": { name: "sloth_1f9a5", alt: "Sloth", codepoint: "1f9a5" },
  "🦦": { name: "otter_1f9a6", alt: "Otter", codepoint: "1f9a6" },
  "🦧": { name: "orangutan_1f9a7", alt: "Orangutan", codepoint: "1f9a7" },
  "🦨": { name: "skunk_1f9a8", alt: "Skunk", codepoint: "1f9a8" },
  "🦩": { name: "flamingo_1f9a9", alt: "Flamingo", codepoint: "1f9a9" },
  "🦫": { name: "beaver_1f9ab", alt: "Beaver", codepoint: "1f9ab" },
  "🦬": { name: "bison_1f9ac", alt: "Bison", codepoint: "1f9ac" },
  "🦭": { name: "seal_1f9ad", alt: "Seal", codepoint: "1f9ad" },
  "🦮": { name: "guide-dog_1f9ae", alt: "Guide dog", codepoint: "1f9ae" },
  "🪰": { name: "fly_1fab0", alt: "Fly", codepoint: "1fab0" },
  "🪱": { name: "worm_1fab1", alt: "Worm", codepoint: "1fab1" },
  "🪲": { name: "beetle_1fab2", alt: "Beetle", codepoint: "1fab2" },
  "🪳": { name: "cockroach_1fab3", alt: "Cockroach", codepoint: "1fab3" },
  "🪴": { name: "potted-plant_1fab4", alt: "Potted plant", codepoint: "1fab4" },
  "🪶": { name: "feather_1fab6", alt: "Feather", codepoint: "1fab6" },
  "🪷": { name: "lotus_1fab7", alt: "Lotus", codepoint: "1fab7" },
  "🪸": { name: "coral_1fab8", alt: "Coral", codepoint: "1fab8" },
  "🪹": { name: "empty-nest_1fab9", alt: "Empty nest", codepoint: "1fab9" },
  "🪺": { name: "nest-with-eggs_1faba", alt: "Nest with eggs", codepoint: "1faba" },
  "🪻": { name: "hyacinth_1fabb", alt: "Hyacinth", codepoint: "1fabb" },
  "🪼": { name: "jellyfish_1fabc", alt: "Jellyfish", codepoint: "1fabc" },
  "🪽": { name: "wing_1fabd", alt: "Wing", codepoint: "1fabd" },
  "🪿": { name: "goose_1fabf", alt: "Goose", codepoint: "1fabf" },
  "🫎": { name: "moose_1face", alt: "Moose", codepoint: "1face" },
  "🫏": { name: "donkey_1facf", alt: "Donkey", codepoint: "1facf" },

  // ─── Activities (58) ───
  "🎀": { name: "ribbon_1f380", alt: "Ribbon", codepoint: "1f380" },
  "🎃": { name: "jack-o-lantern_1f383", alt: "Jack-o-lantern", codepoint: "1f383" },
  "🎄": { name: "christmas-tree_1f384", alt: "Christmas tree", codepoint: "1f384" },
  "🎆": { name: "fireworks_1f386", alt: "Fireworks", codepoint: "1f386" },
  "🎇": { name: "sparkler_1f387", alt: "Firework sparkler", codepoint: "1f387" },
  "🎈": { name: "balloon_1f388", alt: "Balloon", codepoint: "1f388" },
  "🎉": { name: "party-popper_1f389", alt: "Party popper", codepoint: "1f389" },
  "🎊": { name: "confetti-ball_1f38a", alt: "Confetti ball", codepoint: "1f38a" },
  "🎋": { name: "tanabata-tree_1f38b", alt: "Tanabata tree", codepoint: "1f38b" },
  "🎍": { name: "pine-decoration_1f38d", alt: "Pine decoration", codepoint: "1f38d" },
  "🎎": { name: "japanese-dolls_1f38e", alt: "Japanese dolls", codepoint: "1f38e" },
  "🎏": { name: "carp-streamer_1f38f", alt: "Carp streamer", codepoint: "1f38f" },
  "🎐": { name: "wind-chime_1f390", alt: "Wind chime", codepoint: "1f390" },
  "🎑": { name: "moon-viewing-ceremony_1f391", alt: "Moon viewing ceremony", codepoint: "1f391" },
  "🎨": { name: "artist-palette_1f3a8", alt: "Artist palette", codepoint: "1f3a8" },
  "🎫": { name: "ticket_1f3ab", alt: "Ticket", codepoint: "1f3ab" },
  "🎭": { name: "performing-arts_1f3ad", alt: "Performing arts", codepoint: "1f3ad" },
  "🎮": { name: "video-game_1f3ae", alt: "Video game", codepoint: "1f3ae" },
  "🎯": { name: "direct-hit_1f3af", alt: "Direct hit", codepoint: "1f3af" },
  "🎰": { name: "slot-machine_1f3b0", alt: "Slot machine", codepoint: "1f3b0" },
  "🎲": { name: "game-die_1f3b2", alt: "Game die", codepoint: "1f3b2" },
  "🎳": { name: "bowling_1f3b3", alt: "Bowling", codepoint: "1f3b3" },
  "🎴": { name: "flower-playing-cards_1f3b4", alt: "Flower playing cards", codepoint: "1f3b4" },
  "🎾": { name: "tennis_1f3be", alt: "Tennis racquet and ball", codepoint: "1f3be" },
  "🏀": { name: "basketball_1f3c0", alt: "Basketball and hoop", codepoint: "1f3c0" },
  "🏅": { name: "sports-medal_1f3c5", alt: "Sports medal", codepoint: "1f3c5" },
  "🏆": { name: "trophy_1f3c6", alt: "Trophy", codepoint: "1f3c6" },
  "🏈": { name: "american-football_1f3c8", alt: "American football", codepoint: "1f3c8" },
  "🏉": { name: "rugby-football_1f3c9", alt: "Rugby football", codepoint: "1f3c9" },
  "🏐": { name: "volleyball_1f3d0", alt: "Volleyball", codepoint: "1f3d0" },
  "🔫": { name: "pistol_1f52b", alt: "Pistol", codepoint: "1f52b" },
  "🔮": { name: "crystal-ball_1f52e", alt: "Crystal ball", codepoint: "1f52e" },
  "🛷": { name: "sled_1f6f7", alt: "Sled", codepoint: "1f6f7" },
  "🤿": { name: "diving-mask_1f93f", alt: "Diving mask", codepoint: "1f93f" },
  "🥅": { name: "goal-net_1f945", alt: "Goal net", codepoint: "1f945" },
  "🥊": { name: "boxing-glove_1f94a", alt: "Boxing glove", codepoint: "1f94a" },
  "🥋": { name: "martial-arts-uniform_1f94b", alt: "Martial arts uniform", codepoint: "1f94b" },
  "🥌": { name: "curling-stone_1f94c", alt: "Curling stone", codepoint: "1f94c" },
  "🥍": { name: "lacrosse_1f94d", alt: "Lacrosse stick and ball", codepoint: "1f94d" },
  "🥎": { name: "softball_1f94e", alt: "Softball", codepoint: "1f94e" },
  "🥏": { name: "flying-disc_1f94f", alt: "Flying disc", codepoint: "1f94f" },
  "🧧": { name: "red-envelope_1f9e7", alt: "Red gift envelope", codepoint: "1f9e7" },
  "🧨": { name: "firecracker_1f9e8", alt: "Firecracker", codepoint: "1f9e8" },
  "🧵": { name: "thread_1f9f5", alt: "Spool of thread", codepoint: "1f9f5" },
  "🧶": { name: "yarn_1f9f6", alt: "Ball of yarn", codepoint: "1f9f6" },
  "🧸": { name: "teddy-bear_1f9f8", alt: "Teddy bear", codepoint: "1f9f8" },
  "🪀": { name: "yo-yo_1fa80", alt: "Yo-yo", codepoint: "1fa80" },
  "🪁": { name: "kite_1fa81", alt: "Kite", codepoint: "1fa81" },
  "🪄": { name: "magic-wand_1fa84", alt: "Magic wand", codepoint: "1fa84" },
  "🪅": { name: "pinata_1fa85", alt: "Pinata", codepoint: "1fa85" },
  "🪆": { name: "nesting-dolls_1fa86", alt: "Nesting dolls", codepoint: "1fa86" },
  "🪡": { name: "sewing-needle_1faa1", alt: "Sewing needle", codepoint: "1faa1" },
  "🪢": { name: "knot_1faa2", alt: "Knot", codepoint: "1faa2" },
  "🪩": { name: "mirror-ball_1faa9", alt: "Mirror ball", codepoint: "1faa9" },
  "⚽": { name: "soccer-ball_26bd", alt: "Soccer ball", codepoint: "26bd" },
  "⚾": { name: "baseball_26be", alt: "Baseball", codepoint: "26be" },
  "⛳": { name: "flag-in-hole_26f3", alt: "Flag in hole", codepoint: "26f3" },
  "✨": { name: "sparkles_2728", alt: "Sparkles", codepoint: "2728" },

  // ─── Objects (175) ───
  "🎓": { name: "graduation-cap_1f393", alt: "Graduation cap", codepoint: "1f393" },
  "🎤": { name: "microphone_1f3a4", alt: "Microphone", codepoint: "1f3a4" },
  "🎥": { name: "movie-camera_1f3a5", alt: "Movie camera", codepoint: "1f3a5" },
  "🎧": { name: "headphone_1f3a7", alt: "Headphone", codepoint: "1f3a7" },
  "🎩": { name: "top-hat_1f3a9", alt: "Top hat", codepoint: "1f3a9" },
  "🎬": { name: "clapper-board_1f3ac", alt: "Clapper board", codepoint: "1f3ac" },
  "🎵": { name: "musical-note_1f3b5", alt: "Musical note", codepoint: "1f3b5" },
  "🎷": { name: "saxophone_1f3b7", alt: "Saxophone", codepoint: "1f3b7" },
  "🎸": { name: "guitar_1f3b8", alt: "Guitar", codepoint: "1f3b8" },
  "🎹": { name: "musical-keyboard_1f3b9", alt: "Musical keyboard", codepoint: "1f3b9" },
  "🎺": { name: "trumpet_1f3ba", alt: "Trumpet", codepoint: "1f3ba" },
  "🎻": { name: "violin_1f3bb", alt: "Violin", codepoint: "1f3bb" },
  "🎼": { name: "musical-score_1f3bc", alt: "Musical score", codepoint: "1f3bc" },
  "🏹": { name: "bow-and-arrow_1f3f9", alt: "Bow and arrow", codepoint: "1f3f9" },
  "👑": { name: "crown_1f451", alt: "Crown", codepoint: "1f451" },
  "👒": { name: "womans-hat_1f452", alt: "Womans hat", codepoint: "1f452" },
  "👔": { name: "necktie_1f454", alt: "Necktie", codepoint: "1f454" },
  "👕": { name: "t-shirt_1f455", alt: "T-shirt", codepoint: "1f455" },
  "👖": { name: "jeans_1f456", alt: "Jeans", codepoint: "1f456" },
  "👗": { name: "dress_1f457", alt: "Dress", codepoint: "1f457" },
  "👘": { name: "kimono_1f458", alt: "Kimono", codepoint: "1f458" },
  "👙": { name: "bikini_1f459", alt: "Bikini", codepoint: "1f459" },
  "👚": { name: "womans-clothes_1f45a", alt: "Womans clothes", codepoint: "1f45a" },
  "👛": { name: "purse_1f45b", alt: "Purse", codepoint: "1f45b" },
  "👜": { name: "handbag_1f45c", alt: "Handbag", codepoint: "1f45c" },
  "👞": { name: "mans-shoe_1f45e", alt: "Mans shoe", codepoint: "1f45e" },
  "👠": { name: "high-heeled-shoe_1f460", alt: "High-heeled shoe", codepoint: "1f460" },
  "👡": { name: "womans-sandal_1f461", alt: "Womans sandal", codepoint: "1f461" },
  "💄": { name: "lipstick_1f484", alt: "Lipstick", codepoint: "1f484" },
  "💉": { name: "syringe_1f489", alt: "Syringe", codepoint: "1f489" },
  "💊": { name: "pill_1f48a", alt: "Pill", codepoint: "1f48a" },
  "💍": { name: "ring_1f48d", alt: "Ring", codepoint: "1f48d" },
  "💎": { name: "gem-stone_1f48e", alt: "Gem stone", codepoint: "1f48e" },
  "💣": { name: "bomb_1f4a3", alt: "Bomb", codepoint: "1f4a3" },
  "💰": { name: "money-bag_1f4b0", alt: "Money bag", codepoint: "1f4b0" },
  "💳": { name: "credit-card_1f4b3", alt: "Credit card", codepoint: "1f4b3" },
  "💸": { name: "money-with-wings_1f4b8", alt: "Money with wings", codepoint: "1f4b8" },
  "💼": { name: "briefcase_1f4bc", alt: "Briefcase", codepoint: "1f4bc" },
  "💾": { name: "floppy-disk_1f4be", alt: "Floppy disk", codepoint: "1f4be" },
  "📀": { name: "dvd_1f4c0", alt: "Dvd", codepoint: "1f4c0" },
  "📁": { name: "file-folder_1f4c1", alt: "File folder", codepoint: "1f4c1" },
  "📂": { name: "open-file-folder_1f4c2", alt: "Open file folder", codepoint: "1f4c2" },
  "📃": { name: "page-with-curl_1f4c3", alt: "Page with curl", codepoint: "1f4c3" },
  "📄": { name: "page-facing-up_1f4c4", alt: "Page facing up", codepoint: "1f4c4" },
  "📅": { name: "calendar_1f4c5", alt: "Calendar", codepoint: "1f4c5" },
  "📆": { name: "tear-off-calendar_1f4c6", alt: "Tear-off calendar", codepoint: "1f4c6" },
  "📇": { name: "card-index_1f4c7", alt: "Card index", codepoint: "1f4c7" },
  "📊": { name: "bar-chart_1f4ca", alt: "Bar chart", codepoint: "1f4ca" },
  "📋": { name: "clipboard_1f4cb", alt: "Clipboard", codepoint: "1f4cb" },
  "📌": { name: "pushpin_1f4cc", alt: "Pushpin", codepoint: "1f4cc" },
  "📍": { name: "round-pushpin_1f4cd", alt: "Round pushpin", codepoint: "1f4cd" },
  "📎": { name: "paperclip_1f4ce", alt: "Paperclip", codepoint: "1f4ce" },
  "📏": { name: "straight-ruler_1f4cf", alt: "Straight ruler", codepoint: "1f4cf" },
  "📐": { name: "triangular-ruler_1f4d0", alt: "Triangular ruler", codepoint: "1f4d0" },
  "📑": { name: "bookmark-tabs_1f4d1", alt: "Bookmark tabs", codepoint: "1f4d1" },
  "📒": { name: "ledger_1f4d2", alt: "Ledger", codepoint: "1f4d2" },
  "📓": { name: "notebook_1f4d3", alt: "Notebook", codepoint: "1f4d3" },
  "📔": { name: "notebook-with-decorative-cover_1f4d4", alt: "Notebook with decorative cover", codepoint: "1f4d4" },
  "📕": { name: "closed-book_1f4d5", alt: "Closed book", codepoint: "1f4d5" },
  "📖": { name: "open-book_1f4d6", alt: "Open book", codepoint: "1f4d6" },
  "📗": { name: "green-book_1f4d7", alt: "Green book", codepoint: "1f4d7" },
  "📘": { name: "blue-book_1f4d8", alt: "Blue book", codepoint: "1f4d8" },
  "📙": { name: "orange-book_1f4d9", alt: "Orange book", codepoint: "1f4d9" },
  "📚": { name: "books_1f4da", alt: "Books", codepoint: "1f4da" },
  "📜": { name: "scroll_1f4dc", alt: "Scroll", codepoint: "1f4dc" },
  "📝": { name: "memo_1f4dd", alt: "Memo", codepoint: "1f4dd" },
  "📞": { name: "telephone-receiver_1f4de", alt: "Telephone receiver", codepoint: "1f4de" },
  "📟": { name: "pager_1f4df", alt: "Pager", codepoint: "1f4df" },
  "📠": { name: "fax-machine_1f4e0", alt: "Fax machine", codepoint: "1f4e0" },
  "📡": { name: "satellite-antenna_1f4e1", alt: "Satellite antenna", codepoint: "1f4e1" },
  "📢": { name: "loudspeaker_1f4e2", alt: "Public address loudspeaker", codepoint: "1f4e2" },
  "📤": { name: "outbox-tray_1f4e4", alt: "Outbox tray", codepoint: "1f4e4" },
  "📥": { name: "inbox-tray_1f4e5", alt: "Inbox tray", codepoint: "1f4e5" },
  "📦": { name: "package_1f4e6", alt: "Package", codepoint: "1f4e6" },
  "📧": { name: "e-mail_1f4e7", alt: "E-mail symbol", codepoint: "1f4e7" },
  "📨": { name: "incoming-envelope_1f4e8", alt: "Incoming envelope", codepoint: "1f4e8" },
  "📩": { name: "envelope-with-arrow_1f4e9", alt: "Envelope with downwards arrow above", codepoint: "1f4e9" },
  "📪": { name: "closed-mailbox-with-lowered-flag_1f4ea", alt: "Closed mailbox with lowered flag", codepoint: "1f4ea" },
  "📫": { name: "closed-mailbox-with-raised-flag_1f4eb", alt: "Closed mailbox with raised flag", codepoint: "1f4eb" },
  "📬": { name: "open-mailbox-with-raised-flag_1f4ec", alt: "Open mailbox with raised flag", codepoint: "1f4ec" },
  "📭": { name: "open-mailbox-with-lowered-flag_1f4ed", alt: "Open mailbox with lowered flag", codepoint: "1f4ed" },
  "📮": { name: "postbox_1f4ee", alt: "Postbox", codepoint: "1f4ee" },
  "📯": { name: "postal-horn_1f4ef", alt: "Postal horn", codepoint: "1f4ef" },
  "📰": { name: "newspaper_1f4f0", alt: "Newspaper", codepoint: "1f4f0" },
  "📱": { name: "mobile-phone_1f4f1", alt: "Mobile phone", codepoint: "1f4f1" },
  "📷": { name: "camera_1f4f7", alt: "Camera", codepoint: "1f4f7" },
  "📸": { name: "camera-with-flash_1f4f8", alt: "Camera with flash", codepoint: "1f4f8" },
  "📹": { name: "video-camera_1f4f9", alt: "Video camera", codepoint: "1f4f9" },
  "📺": { name: "television_1f4fa", alt: "Television", codepoint: "1f4fa" },
  "📻": { name: "radio_1f4fb", alt: "Radio", codepoint: "1f4fb" },
  "📼": { name: "videocassette_1f4fc", alt: "Videocassette", codepoint: "1f4fc" },
  "📿": { name: "prayer-beads_1f4ff", alt: "Prayer beads", codepoint: "1f4ff" },
  "🔋": { name: "battery_1f50b", alt: "Battery", codepoint: "1f50b" },
  "🔌": { name: "electric-plug_1f50c", alt: "Electric plug", codepoint: "1f50c" },
  "🔑": { name: "key_1f511", alt: "Key", codepoint: "1f511" },
  "🔔": { name: "bell_1f514", alt: "Bell", codepoint: "1f514" },
  "🔖": { name: "bookmark_1f516", alt: "Bookmark", codepoint: "1f516" },
  "🔗": { name: "link_1f517", alt: "Link symbol", codepoint: "1f517" },
  "🔦": { name: "flashlight_1f526", alt: "Electric torch", codepoint: "1f526" },
  "🔧": { name: "wrench_1f527", alt: "Wrench", codepoint: "1f527" },
  "🔨": { name: "hammer_1f528", alt: "Hammer", codepoint: "1f528" },
  "🔩": { name: "nut-and-bolt_1f529", alt: "Nut and bolt", codepoint: "1f529" },
  "🔬": { name: "microscope_1f52c", alt: "Microscope", codepoint: "1f52c" },
  "🔭": { name: "telescope_1f52d", alt: "Telescope", codepoint: "1f52d" },
  "🚪": { name: "door_1f6aa", alt: "Door", codepoint: "1f6aa" },
  "🚽": { name: "toilet_1f6bd", alt: "Toilet", codepoint: "1f6bd" },
  "🚿": { name: "shower_1f6bf", alt: "Shower", codepoint: "1f6bf" },
  "🛁": { name: "bathtub_1f6c1", alt: "Bathtub", codepoint: "1f6c1" },
  "🛗": { name: "elevator_1f6d7", alt: "Elevator", codepoint: "1f6d7" },
  "🥻": { name: "sari_1f97b", alt: "Sari", codepoint: "1f97b" },
  "🥼": { name: "lab-coat_1f97c", alt: "Lab coat", codepoint: "1f97c" },
  "🥽": { name: "goggles_1f97d", alt: "Goggles", codepoint: "1f97d" },
  "🥾": { name: "hiking-boot_1f97e", alt: "Hiking boot", codepoint: "1f97e" },
  "🥿": { name: "flat-shoe_1f97f", alt: "Flat shoe", codepoint: "1f97f" },
  "🦺": { name: "safety-vest_1f9ba", alt: "Safety vest", codepoint: "1f9ba" },
  "🧢": { name: "billed-cap_1f9e2", alt: "Billed cap", codepoint: "1f9e2" },
  "🧣": { name: "scarf_1f9e3", alt: "Scarf", codepoint: "1f9e3" },
  "🧤": { name: "gloves_1f9e4", alt: "Gloves", codepoint: "1f9e4" },
  "🧥": { name: "coat_1f9e5", alt: "Coat", codepoint: "1f9e5" },
  "🧦": { name: "socks_1f9e6", alt: "Socks", codepoint: "1f9e6" },
  "🧪": { name: "test-tube_1f9ea", alt: "Test tube", codepoint: "1f9ea" },
  "🧫": { name: "petri-dish_1f9eb", alt: "Petri dish", codepoint: "1f9eb" },
  "🧬": { name: "dna_1f9ec", alt: "Dna double helix", codepoint: "1f9ec" },
  "🧮": { name: "abacus_1f9ee", alt: "Abacus", codepoint: "1f9ee" },
  "🧯": { name: "fire-extinguisher_1f9ef", alt: "Fire extinguisher", codepoint: "1f9ef" },
  "🧰": { name: "toolbox_1f9f0", alt: "Toolbox", codepoint: "1f9f0" },
  "🧲": { name: "magnet_1f9f2", alt: "Magnet", codepoint: "1f9f2" },
  "🧴": { name: "lotion-bottle_1f9f4", alt: "Lotion bottle", codepoint: "1f9f4" },
  "🧷": { name: "safety-pin_1f9f7", alt: "Safety pin", codepoint: "1f9f7" },
  "🧹": { name: "broom_1f9f9", alt: "Broom", codepoint: "1f9f9" },
  "🧺": { name: "basket_1f9fa", alt: "Basket", codepoint: "1f9fa" },
  "🧻": { name: "roll-of-paper_1f9fb", alt: "Roll of paper", codepoint: "1f9fb" },
  "🧼": { name: "soap_1f9fc", alt: "Bar of soap", codepoint: "1f9fc" },
  "🧽": { name: "sponge_1f9fd", alt: "Sponge", codepoint: "1f9fd" },
  "🧾": { name: "receipt_1f9fe", alt: "Receipt", codepoint: "1f9fe" },
  "🧿": { name: "nazar-amulet_1f9ff", alt: "Nazar amulet", codepoint: "1f9ff" },
  "🩰": { name: "ballet-shoes_1fa70", alt: "Ballet shoes", codepoint: "1fa70" },
  "🩱": { name: "one-piece-swimsuit_1fa71", alt: "One-piece swimsuit", codepoint: "1fa71" },
  "🩲": { name: "briefs_1fa72", alt: "Briefs", codepoint: "1fa72" },
  "🩳": { name: "shorts_1fa73", alt: "Shorts", codepoint: "1fa73" },
  "🩴": { name: "thong-sandal_1fa74", alt: "Thong sandal", codepoint: "1fa74" },
  "🩸": { name: "drop-of-blood_1fa78", alt: "Drop of blood", codepoint: "1fa78" },
  "🩺": { name: "stethoscope_1fa7a", alt: "Stethoscope", codepoint: "1fa7a" },
  "🩻": { name: "x-ray_1fa7b", alt: "X-ray", codepoint: "1fa7b" },
  "🩼": { name: "crutch_1fa7c", alt: "Crutch", codepoint: "1fa7c" },
  "🪃": { name: "boomerang_1fa83", alt: "Boomerang", codepoint: "1fa83" },
  "🪇": { name: "maracas_1fa87", alt: "Maracas", codepoint: "1fa87" },
  "🪈": { name: "flute_1fa88", alt: "Flute", codepoint: "1fa88" },
  "🪑": { name: "chair_1fa91", alt: "Chair", codepoint: "1fa91" },
  "🪒": { name: "razor_1fa92", alt: "Razor", codepoint: "1fa92" },
  "🪓": { name: "axe_1fa93", alt: "Axe", codepoint: "1fa93" },
  "🪔": { name: "diya-lamp_1fa94", alt: "Diya lamp", codepoint: "1fa94" },
  "🪕": { name: "banjo_1fa95", alt: "Banjo", codepoint: "1fa95" },
  "🪖": { name: "military-helmet_1fa96", alt: "Military helmet", codepoint: "1fa96" },
  "🪗": { name: "accordion_1fa97", alt: "Accordion", codepoint: "1fa97" },
  "🪘": { name: "long-drum_1fa98", alt: "Long drum", codepoint: "1fa98" },
  "🪙": { name: "coin_1fa99", alt: "Coin", codepoint: "1fa99" },
  "🪚": { name: "carpentry-saw_1fa9a", alt: "Carpentry saw", codepoint: "1fa9a" },
  "🪛": { name: "screwdriver_1fa9b", alt: "Screwdriver", codepoint: "1fa9b" },
  "🪜": { name: "ladder_1fa9c", alt: "Ladder", codepoint: "1fa9c" },
  "🪝": { name: "hook_1fa9d", alt: "Hook", codepoint: "1fa9d" },
  "🪞": { name: "mirror_1fa9e", alt: "Mirror", codepoint: "1fa9e" },
  "🪟": { name: "window_1fa9f", alt: "Window", codepoint: "1fa9f" },
  "🪠": { name: "plunger_1faa0", alt: "Plunger", codepoint: "1faa0" },
  "🪣": { name: "bucket_1faa3", alt: "Bucket", codepoint: "1faa3" },
  "🪤": { name: "mouse-trap_1faa4", alt: "Mouse trap", codepoint: "1faa4" },
  "🪥": { name: "toothbrush_1faa5", alt: "Toothbrush", codepoint: "1faa5" },
  "🪦": { name: "headstone_1faa6", alt: "Headstone", codepoint: "1faa6" },
  "🪧": { name: "placard_1faa7", alt: "Placard", codepoint: "1faa7" },
  "🪪": { name: "identification-card_1faaa", alt: "Identification card", codepoint: "1faaa" },
  "🪫": { name: "low-battery_1faab", alt: "Low battery", codepoint: "1faab" },
  "🪬": { name: "hamsa_1faac", alt: "Hamsa", codepoint: "1faac" },
  "🪭": { name: "folding-hand-fan_1faad", alt: "Folding hand fan", codepoint: "1faad" },
  "🪮": { name: "hair-pick_1faae", alt: "Hair pick", codepoint: "1faae" },
  "🫧": { name: "bubbles_1fae7", alt: "Bubbles", codepoint: "1fae7" },

  // ─── Symbols (70) ───
  "🎦": { name: "cinema_1f3a6", alt: "Cinema", codepoint: "1f3a6" },
  "💱": { name: "currency-exchange_1f4b1", alt: "Currency exchange", codepoint: "1f4b1" },
  "💲": { name: "heavy-dollar-sign_1f4b2", alt: "Heavy dollar sign", codepoint: "1f4b2" },
  "📛": { name: "name-badge_1f4db", alt: "Name badge", codepoint: "1f4db" },
  "📳": { name: "vibration-mode_1f4f3", alt: "Vibration mode", codepoint: "1f4f3" },
  "📴": { name: "mobile-phone-off_1f4f4", alt: "Mobile phone off", codepoint: "1f4f4" },
  "📵": { name: "no-mobile-phones_1f4f5", alt: "No mobile phones", codepoint: "1f4f5" },
  "🔘": { name: "radio-button_1f518", alt: "Radio button", codepoint: "1f518" },
  "🔰": { name: "japanese-symbol-for-beginner_1f530", alt: "Japanese symbol for beginner", codepoint: "1f530" },
  "🔱": { name: "trident-emblem_1f531", alt: "Trident emblem", codepoint: "1f531" },
  "🔲": { name: "black-square-button_1f532", alt: "Black square button", codepoint: "1f532" },
  "🔳": { name: "white-square-button_1f533", alt: "White square button", codepoint: "1f533" },
  "🔴": { name: "large-red-circle_1f534", alt: "Large red circle", codepoint: "1f534" },
  "🔵": { name: "large-blue-circle_1f535", alt: "Large blue circle", codepoint: "1f535" },
  "🔶": { name: "large-orange-diamond_1f536", alt: "Large orange diamond", codepoint: "1f536" },
  "🔷": { name: "large-blue-diamond_1f537", alt: "Large blue diamond", codepoint: "1f537" },
  "🔸": { name: "small-orange-diamond_1f538", alt: "Small orange diamond", codepoint: "1f538" },
  "🔹": { name: "small-blue-diamond_1f539", alt: "Small blue diamond", codepoint: "1f539" },
  "🚭": { name: "no-smoking_1f6ad", alt: "No smoking symbol", codepoint: "1f6ad" },
  "🚰": { name: "potable-water_1f6b0", alt: "Potable water symbol", codepoint: "1f6b0" },
  "🚱": { name: "non-potable-water_1f6b1", alt: "Non-potable water symbol", codepoint: "1f6b1" },
  "🚳": { name: "no-bicycles_1f6b3", alt: "No bicycles", codepoint: "1f6b3" },
  "🚷": { name: "no-pedestrians_1f6b7", alt: "No pedestrians", codepoint: "1f6b7" },
  "🚸": { name: "children-crossing_1f6b8", alt: "Children crossing", codepoint: "1f6b8" },
  "🚻": { name: "restroom_1f6bb", alt: "Restroom", codepoint: "1f6bb" },
  "🚼": { name: "baby-symbol_1f6bc", alt: "Baby symbol", codepoint: "1f6bc" },
  "🚾": { name: "water-closet_1f6be", alt: "Water closet", codepoint: "1f6be" },
  "🛂": { name: "passport-control_1f6c2", alt: "Passport control", codepoint: "1f6c2" },
  "🛃": { name: "customs_1f6c3", alt: "Customs", codepoint: "1f6c3" },
  "🛄": { name: "baggage-claim_1f6c4", alt: "Baggage claim", codepoint: "1f6c4" },
  "🛅": { name: "left-luggage_1f6c5", alt: "Left luggage", codepoint: "1f6c5" },
  "🛐": { name: "place-of-worship_1f6d0", alt: "Place of worship", codepoint: "1f6d0" },
  "🛜": { name: "wireless_1f6dc", alt: "Wireless", codepoint: "1f6dc" },
  "🟠": { name: "large-orange-circle_1f7e0", alt: "Large orange circle", codepoint: "1f7e0" },
  "🟡": { name: "large-yellow-circle_1f7e1", alt: "Large yellow circle", codepoint: "1f7e1" },
  "🟢": { name: "large-green-circle_1f7e2", alt: "Large green circle", codepoint: "1f7e2" },
  "🟣": { name: "large-purple-circle_1f7e3", alt: "Large purple circle", codepoint: "1f7e3" },
  "🟤": { name: "large-brown-circle_1f7e4", alt: "Large brown circle", codepoint: "1f7e4" },
  "🟥": { name: "large-red-square_1f7e5", alt: "Large red square", codepoint: "1f7e5" },
  "🟦": { name: "large-blue-square_1f7e6", alt: "Large blue square", codepoint: "1f7e6" },
  "🟧": { name: "large-orange-square_1f7e7", alt: "Large orange square", codepoint: "1f7e7" },
  "🟨": { name: "large-yellow-square_1f7e8", alt: "Large yellow square", codepoint: "1f7e8" },
  "🟩": { name: "large-green-square_1f7e9", alt: "Large green square", codepoint: "1f7e9" },
  "🟪": { name: "large-purple-square_1f7ea", alt: "Large purple square", codepoint: "1f7ea" },
  "🟫": { name: "large-brown-square_1f7eb", alt: "Large brown square", codepoint: "1f7eb" },
  "🟰": { name: "heavy-equals-sign_1f7f0", alt: "Heavy equals sign", codepoint: "1f7f0" },
  "🪯": { name: "khanda_1faaf", alt: "Khanda", codepoint: "1faaf" },
  "◽": { name: "white-medium-small-square_25fd", alt: "White medium small square", codepoint: "25fd" },
  "◾": { name: "black-medium-small-square_25fe", alt: "Black medium small square", codepoint: "25fe" },
  "♈": { name: "aries_2648", alt: "Aries", codepoint: "2648" },
  "♉": { name: "taurus_2649", alt: "Taurus", codepoint: "2649" },
  "♊": { name: "gemini_264a", alt: "Gemini", codepoint: "264a" },
  "♋": { name: "cancer_264b", alt: "Cancer", codepoint: "264b" },
  "♌": { name: "leo_264c", alt: "Leo", codepoint: "264c" },
  "♍": { name: "virgo_264d", alt: "Virgo", codepoint: "264d" },
  "♎": { name: "libra_264e", alt: "Libra", codepoint: "264e" },
  "♐": { name: "sagittarius_2650", alt: "Sagittarius", codepoint: "2650" },
  "♑": { name: "capricorn_2651", alt: "Capricorn", codepoint: "2651" },
  "♒": { name: "aquarius_2652", alt: "Aquarius", codepoint: "2652" },
  "♓": { name: "pisces_2653", alt: "Pisces", codepoint: "2653" },
  "♿": { name: "wheelchair-symbol_267f", alt: "Wheelchair symbol", codepoint: "267f" },
  "⚪": { name: "white-circle_26aa", alt: "Medium white circle", codepoint: "26aa" },
  "⚫": { name: "black-circle_26ab", alt: "Medium black circle", codepoint: "26ab" },
  "⛎": { name: "ophiuchus_26ce", alt: "Ophiuchus", codepoint: "26ce" },
  "⛔": { name: "no-entry_26d4", alt: "No entry", codepoint: "26d4" },
  "❌": { name: "cross-mark_274c", alt: "Cross mark", codepoint: "274c" },
  "➰": { name: "curly-loop_27b0", alt: "Curly loop", codepoint: "27b0" },
  "➿": { name: "double-curly-loop_27bf", alt: "Double curly loop", codepoint: "27bf" },
  "⬛": { name: "black-large-square_2b1b", alt: "Black large square", codepoint: "2b1b" },
  "⬜": { name: "white-large-square_2b1c", alt: "White large square", codepoint: "2b1c" },

  // ─── People & Body (89) ───
  "🏂": { name: "snowboarder_1f3c2", alt: "Snowboarder", codepoint: "1f3c2" },
  "🏇": { name: "horse-racing_1f3c7", alt: "Horse racing", codepoint: "1f3c7" },
  "👀": { name: "eyes_1f440", alt: "Eyes", codepoint: "1f440" },
  "👂": { name: "ear_1f442", alt: "Ear", codepoint: "1f442" },
  "👃": { name: "nose_1f443", alt: "Nose", codepoint: "1f443" },
  "👄": { name: "mouth_1f444", alt: "Mouth", codepoint: "1f444" },
  "👅": { name: "tongue_1f445", alt: "Tongue", codepoint: "1f445" },
  "👌": { name: "ok-hand_1f44c", alt: "Ok hand sign", codepoint: "1f44c" },
  "👐": { name: "open-hands_1f450", alt: "Open hands sign", codepoint: "1f450" },
  "👣": { name: "footprints_1f463", alt: "Footprints", codepoint: "1f463" },
  "👤": { name: "bust-in-silhouette_1f464", alt: "Bust in silhouette", codepoint: "1f464" },
  "👥": { name: "busts-in-silhouette_1f465", alt: "Busts in silhouette", codepoint: "1f465" },
  "👦": { name: "boy_1f466", alt: "Boy", codepoint: "1f466" },
  "👧": { name: "girl_1f467", alt: "Girl", codepoint: "1f467" },
  "👩": { name: "woman_1f469", alt: "Woman", codepoint: "1f469" },
  "👪": { name: "family_1f46a", alt: "Family", codepoint: "1f46a" },
  "👫": { name: "woman-and-man-holding-hands_1f46b", alt: "Man and woman holding hands", codepoint: "1f46b" },
  "👬": { name: "men-holding-hands_1f46c", alt: "Two men holding hands", codepoint: "1f46c" },
  "👭": { name: "women-holding-hands_1f46d", alt: "Two women holding hands", codepoint: "1f46d" },
  "👮": { name: "police-officer_1f46e", alt: "Police officer", codepoint: "1f46e" },
  "👶": { name: "baby_1f476", alt: "Baby", codepoint: "1f476" },
  "👷": { name: "construction-worker_1f477", alt: "Construction worker", codepoint: "1f477" },
  "👸": { name: "princess_1f478", alt: "Princess", codepoint: "1f478" },
  "👼": { name: "baby-angel_1f47c", alt: "Baby angel", codepoint: "1f47c" },
  "💅": { name: "nail-polish_1f485", alt: "Nail polish", codepoint: "1f485" },
  "💏": { name: "kiss_1f48f", alt: "Kiss", codepoint: "1f48f" },
  "💑": { name: "couple-with-heart_1f491", alt: "Couple with heart", codepoint: "1f491" },
  "❤️": { name: "red-heart_2764-fe0f", alt: "Red heart", codepoint: "2764-fe0f" },
  "❤": { name: "red-heart_2764", alt: "Red heart", codepoint: "2764" },
  "💪": { name: "flexed-biceps_1f4aa", alt: "Flexed biceps", codepoint: "1f4aa" },
  "🕺": { name: "man-dancing_1f57a", alt: "Man dancing", codepoint: "1f57a" },
  "🖕": { name: "middle-finger_1f595", alt: "Reversed hand with middle finger extended", codepoint: "1f595" },
  "🙍": { name: "person-frowning_1f64d", alt: "Person frowning", codepoint: "1f64d" },
  "🤌": { name: "pinched-fingers_1f90c", alt: "Pinched fingers", codepoint: "1f90c" },
  "🤏": { name: "pinching-hand_1f90f", alt: "Pinching hand", codepoint: "1f90f" },
  "🤘": { name: "sign-of-the-horns_1f918", alt: "Sign of the horns", codepoint: "1f918" },
  "🤙": { name: "call-me-hand_1f919", alt: "Call me hand", codepoint: "1f919" },
  "🤚": { name: "raised-back-of-hand_1f91a", alt: "Raised back of hand", codepoint: "1f91a" },
  "🤛": { name: "left-facing-fist_1f91b", alt: "Left-facing fist", codepoint: "1f91b" },
  "🤜": { name: "right-facing-fist_1f91c", alt: "Right-facing fist", codepoint: "1f91c" },
  "🤝": { name: "handshake_1f91d", alt: "Handshake", codepoint: "1f91d" },
  "🤞": { name: "crossed-fingers_1f91e", alt: "Hand with index and middle fingers crossed", codepoint: "1f91e" },
  "🤰": { name: "pregnant-woman_1f930", alt: "Pregnant woman", codepoint: "1f930" },
  "🤱": { name: "breast-feeding_1f931", alt: "Breast-feeding", codepoint: "1f931" },
  "🤲": { name: "palms-up-together_1f932", alt: "Palms up together", codepoint: "1f932" },
  "🤳": { name: "selfie_1f933", alt: "Selfie", codepoint: "1f933" },
  "🤴": { name: "prince_1f934", alt: "Prince", codepoint: "1f934" },
  "🤵": { name: "person-in-tuxedo_1f935", alt: "Man in tuxedo", codepoint: "1f935" },
  "🤶": { name: "mrs-claus_1f936", alt: "Mother christmas", codepoint: "1f936" },
  "🥷": { name: "ninja_1f977", alt: "Ninja", codepoint: "1f977" },
  "🦴": { name: "bone_1f9b4", alt: "Bone", codepoint: "1f9b4" },
  "🦵": { name: "leg_1f9b5", alt: "Leg", codepoint: "1f9b5" },
  "🦶": { name: "foot_1f9b6", alt: "Foot", codepoint: "1f9b6" },
  "🦷": { name: "tooth_1f9b7", alt: "Tooth", codepoint: "1f9b7" },
  "🦸": { name: "superhero_1f9b8", alt: "Superhero", codepoint: "1f9b8" },
  "🦹": { name: "supervillain_1f9b9", alt: "Supervillain", codepoint: "1f9b9" },
  "🦻": { name: "ear-with-hearing-aid_1f9bb", alt: "Ear with hearing aid", codepoint: "1f9bb" },
  "🦾": { name: "mechanical-arm_1f9be", alt: "Mechanical arm", codepoint: "1f9be" },
  "🦿": { name: "mechanical-leg_1f9bf", alt: "Mechanical leg", codepoint: "1f9bf" },
  "🧌": { name: "troll_1f9cc", alt: "Troll", codepoint: "1f9cc" },
  "🧏": { name: "deaf-person_1f9cf", alt: "Deaf person", codepoint: "1f9cf" },
  "🧒": { name: "child_1f9d2", alt: "Child", codepoint: "1f9d2" },
  "🧕": { name: "person-with-headscarf_1f9d5", alt: "Person with headscarf", codepoint: "1f9d5" },
  "🧗": { name: "person-climbing_1f9d7", alt: "Person climbing", codepoint: "1f9d7" },
  "🧘": { name: "person-in-lotus-position_1f9d8", alt: "Person in lotus position", codepoint: "1f9d8" },
  "🧙": { name: "mage_1f9d9", alt: "Mage", codepoint: "1f9d9" },
  "🧚": { name: "fairy_1f9da", alt: "Fairy", codepoint: "1f9da" },
  "🧛": { name: "vampire_1f9db", alt: "Vampire", codepoint: "1f9db" },
  "🧜": { name: "merperson_1f9dc", alt: "Merperson", codepoint: "1f9dc" },
  "🧝": { name: "elf_1f9dd", alt: "Elf", codepoint: "1f9dd" },
  "🧞": { name: "genie_1f9de", alt: "Genie", codepoint: "1f9de" },
  "🧟": { name: "zombie_1f9df", alt: "Zombie", codepoint: "1f9df" },
  "🧠": { name: "brain_1f9e0", alt: "Brain", codepoint: "1f9e0" },
  "🫀": { name: "anatomical-heart_1fac0", alt: "Anatomical heart", codepoint: "1fac0" },
  "🫁": { name: "lungs_1fac1", alt: "Lungs", codepoint: "1fac1" },
  "🫂": { name: "people-hugging_1fac2", alt: "People hugging", codepoint: "1fac2" },
  "🫃": { name: "pregnant-man_1fac3", alt: "Pregnant man", codepoint: "1fac3" },
  "🫄": { name: "pregnant-person_1fac4", alt: "Pregnant person", codepoint: "1fac4" },
  "🫅": { name: "person-with-crown_1fac5", alt: "Person with crown", codepoint: "1fac5" },
  "🫦": { name: "biting-lip_1fae6", alt: "Biting lip", codepoint: "1fae6" },
  "🫰": { name: "hand-with-index-finger-and-thumb-crossed_1faf0", alt: "Hand with index finger and thumb crossed", codepoint: "1faf0" },
  "🫱": { name: "rightwards-hand_1faf1", alt: "Rightwards hand", codepoint: "1faf1" },
  "🫲": { name: "leftwards-hand_1faf2", alt: "Leftwards hand", codepoint: "1faf2" },
  "🫳": { name: "palm-down-hand_1faf3", alt: "Palm down hand", codepoint: "1faf3" },
  "🫴": { name: "palm-up-hand_1faf4", alt: "Palm up hand", codepoint: "1faf4" },
  "🫵": { name: "index-pointing-at-the-viewer_1faf5", alt: "Index pointing at the viewer", codepoint: "1faf5" },
  "🫶": { name: "heart-hands_1faf6", alt: "Heart hands", codepoint: "1faf6" },
  "🫷": { name: "leftwards-pushing-hand_1faf7", alt: "Leftwards pushing hand", codepoint: "1faf7" },
  "🫸": { name: "rightwards-pushing-hand_1faf8", alt: "Rightwards pushing hand", codepoint: "1faf8" },
  "✊": { name: "raised-fist_270a", alt: "Raised fist", codepoint: "270a" },
  "✋": { name: "raised-hand_270b", alt: "Raised hand", codepoint: "270b" },

  // ─── Smileys & Emotion (121) ───
  "👻": { name: "ghost_1f47b", alt: "Ghost", codepoint: "1f47b" },
  "👽": { name: "alien_1f47d", alt: "Extraterrestrial alien", codepoint: "1f47d" },
  "👾": { name: "alien-monster_1f47e", alt: "Alien monster", codepoint: "1f47e" },
  "💀": { name: "skull_1f480", alt: "Skull", codepoint: "1f480" },
  "💋": { name: "kiss-mark_1f48b", alt: "Kiss mark", codepoint: "1f48b" },
  "💌": { name: "love-letter_1f48c", alt: "Love letter", codepoint: "1f48c" },
  "💓": { name: "beating-heart_1f493", alt: "Beating heart", codepoint: "1f493" },
  "💔": { name: "broken-heart_1f494", alt: "Broken heart", codepoint: "1f494" },
  "💕": { name: "two-hearts_1f495", alt: "Two hearts", codepoint: "1f495" },
  "💖": { name: "sparkling-heart_1f496", alt: "Sparkling heart", codepoint: "1f496" },
  "💗": { name: "growing-heart_1f497", alt: "Growing heart", codepoint: "1f497" },
  "💘": { name: "heart-with-arrow_1f498", alt: "Heart with arrow", codepoint: "1f498" },
  "💙": { name: "blue-heart_1f499", alt: "Blue heart", codepoint: "1f499" },
  "💚": { name: "green-heart_1f49a", alt: "Green heart", codepoint: "1f49a" },
  "💛": { name: "yellow-heart_1f49b", alt: "Yellow heart", codepoint: "1f49b" },
  "💜": { name: "purple-heart_1f49c", alt: "Purple heart", codepoint: "1f49c" },
  "💝": { name: "heart-with-ribbon_1f49d", alt: "Heart with ribbon", codepoint: "1f49d" },
  "💞": { name: "revolving-hearts_1f49e", alt: "Revolving hearts", codepoint: "1f49e" },
  "💟": { name: "heart-decoration_1f49f", alt: "Heart decoration", codepoint: "1f49f" },
  "💢": { name: "anger-symbol_1f4a2", alt: "Anger symbol", codepoint: "1f4a2" },
  "💤": { name: "zzz_1f4a4", alt: "Sleeping symbol", codepoint: "1f4a4" },
  "💥": { name: "collision_1f4a5", alt: "Collision symbol", codepoint: "1f4a5" },
  "💩": { name: "pile-of-poo_1f4a9", alt: "Pile of poo", codepoint: "1f4a9" },
  "💫": { name: "dizzy_1f4ab", alt: "Dizzy symbol", codepoint: "1f4ab" },
  "💬": { name: "speech-balloon_1f4ac", alt: "Speech balloon", codepoint: "1f4ac" },
  "💭": { name: "thought-balloon_1f4ad", alt: "Thought balloon", codepoint: "1f4ad" },
  "🖤": { name: "black-heart_1f5a4", alt: "Black heart", codepoint: "1f5a4" },
  "😀": { name: "grinning-face_1f600", alt: "Grinning face", codepoint: "1f600" },
  "😂": { name: "face-with-tears-of-joy_1f602", alt: "Face with tears of joy", codepoint: "1f602" },
  "😇": { name: "smiling-face-with-halo_1f607", alt: "Smiling face with halo", codepoint: "1f607" },
  "😈": { name: "smiling-face-with-horns_1f608", alt: "Smiling face with horns", codepoint: "1f608" },
  "😉": { name: "winking-face_1f609", alt: "Winking face", codepoint: "1f609" },
  "😊": { name: "smiling-face-with-smiling-eyes_1f60a", alt: "Smiling face with smiling eyes", codepoint: "1f60a" },
  "😌": { name: "relieved-face_1f60c", alt: "Relieved face", codepoint: "1f60c" },
  "😎": { name: "smiling-face-with-sunglasses_1f60e", alt: "Smiling face with sunglasses", codepoint: "1f60e" },
  "😏": { name: "smirking-face_1f60f", alt: "Smirking face", codepoint: "1f60f" },
  "😐": { name: "neutral-face_1f610", alt: "Neutral face", codepoint: "1f610" },
  "😑": { name: "expressionless-face_1f611", alt: "Expressionless face", codepoint: "1f611" },
  "😒": { name: "unamused-face_1f612", alt: "Unamused face", codepoint: "1f612" },
  "😔": { name: "pensive-face_1f614", alt: "Pensive face", codepoint: "1f614" },
  "😕": { name: "confused-face_1f615", alt: "Confused face", codepoint: "1f615" },
  "😖": { name: "confounded-face_1f616", alt: "Confounded face", codepoint: "1f616" },
  "😗": { name: "kissing-face_1f617", alt: "Kissing face", codepoint: "1f617" },
  "😙": { name: "kissing-face-with-smiling-eyes_1f619", alt: "Kissing face with smiling eyes", codepoint: "1f619" },
  "😚": { name: "kissing-face-with-closed-eyes_1f61a", alt: "Kissing face with closed eyes", codepoint: "1f61a" },
  "😞": { name: "disappointed-face_1f61e", alt: "Disappointed face", codepoint: "1f61e" },
  "😟": { name: "worried-face_1f61f", alt: "Worried face", codepoint: "1f61f" },
  "😠": { name: "angry-face_1f620", alt: "Angry face", codepoint: "1f620" },
  "😡": { name: "pouting-face_1f621", alt: "Pouting face", codepoint: "1f621" },
  "😢": { name: "crying-face_1f622", alt: "Crying face", codepoint: "1f622" },
  "😣": { name: "persevering-face_1f623", alt: "Persevering face", codepoint: "1f623" },
  "😦": { name: "frowning-face-with-open-mouth_1f626", alt: "Frowning face with open mouth", codepoint: "1f626" },
  "😧": { name: "anguished-face_1f627", alt: "Anguished face", codepoint: "1f627" },
  "😨": { name: "fearful-face_1f628", alt: "Fearful face", codepoint: "1f628" },
  "😩": { name: "weary-face_1f629", alt: "Weary face", codepoint: "1f629" },
  "😪": { name: "sleepy-face_1f62a", alt: "Sleepy face", codepoint: "1f62a" },
  "😫": { name: "tired-face_1f62b", alt: "Tired face", codepoint: "1f62b" },
  "😬": { name: "grimacing-face_1f62c", alt: "Grimacing face", codepoint: "1f62c" },
  "😭": { name: "loudly-crying-face_1f62d", alt: "Loudly crying face", codepoint: "1f62d" },
  "😮": { name: "face-with-open-mouth_1f62e", alt: "Face with open mouth", codepoint: "1f62e" },
  "😯": { name: "hushed-face_1f62f", alt: "Hushed face", codepoint: "1f62f" },
  "😱": { name: "face-screaming-in-fear_1f631", alt: "Face screaming in fear", codepoint: "1f631" },
  "😲": { name: "astonished-face_1f632", alt: "Astonished face", codepoint: "1f632" },
  "😳": { name: "flushed-face_1f633", alt: "Flushed face", codepoint: "1f633" },
  "😴": { name: "sleeping-face_1f634", alt: "Sleeping face", codepoint: "1f634" },
  "😵": { name: "dizzy-face_1f635", alt: "Dizzy face", codepoint: "1f635" },
  "😶": { name: "face-without-mouth_1f636", alt: "Face without mouth", codepoint: "1f636" },
  "😷": { name: "face-with-medical-mask_1f637", alt: "Face with medical mask", codepoint: "1f637" },
  "😽": { name: "kissing-cat_1f63d", alt: "Kissing cat face with closed eyes", codepoint: "1f63d" },
  "😾": { name: "pouting-cat_1f63e", alt: "Pouting cat face", codepoint: "1f63e" },
  "🙁": { name: "slightly-frowning-face_1f641", alt: "Slightly frowning face", codepoint: "1f641" },
  "🙂": { name: "slightly-smiling-face_1f642", alt: "Slightly smiling face", codepoint: "1f642" },
  "🙃": { name: "upside-down-face_1f643", alt: "Upside-down face", codepoint: "1f643" },
  "🙄": { name: "face-with-rolling-eyes_1f644", alt: "Face with rolling eyes", codepoint: "1f644" },
  "🙈": { name: "see-no-evil-monkey_1f648", alt: "See-no-evil monkey", codepoint: "1f648" },
  "🙉": { name: "hear-no-evil-monkey_1f649", alt: "Hear-no-evil monkey", codepoint: "1f649" },
  "🙊": { name: "speak-no-evil-monkey_1f64a", alt: "Speak-no-evil monkey", codepoint: "1f64a" },
  "🤍": { name: "white-heart_1f90d", alt: "White heart", codepoint: "1f90d" },
  "🤎": { name: "brown-heart_1f90e", alt: "Brown heart", codepoint: "1f90e" },
  "🤐": { name: "zipper-mouth-face_1f910", alt: "Zipper-mouth face", codepoint: "1f910" },
  "🤑": { name: "money-mouth-face_1f911", alt: "Money-mouth face", codepoint: "1f911" },
  "🤒": { name: "face-with-thermometer_1f912", alt: "Face with thermometer", codepoint: "1f912" },
  "🤓": { name: "nerd-face_1f913", alt: "Nerd face", codepoint: "1f913" },
  "🤔": { name: "thinking-face_1f914", alt: "Thinking face", codepoint: "1f914" },
  "🤕": { name: "face-with-head-bandage_1f915", alt: "Face with head-bandage", codepoint: "1f915" },
  "🤗": { name: "hugging-face_1f917", alt: "Hugging face", codepoint: "1f917" },
  "🤡": { name: "clown-face_1f921", alt: "Clown face", codepoint: "1f921" },
  "🤢": { name: "nauseated-face_1f922", alt: "Nauseated face", codepoint: "1f922" },
  "🤣": { name: "rolling-on-the-floor-laughing_1f923", alt: "Rolling on the floor laughing", codepoint: "1f923" },
  "🤤": { name: "drooling-face_1f924", alt: "Drooling face", codepoint: "1f924" },
  "🤥": { name: "lying-face_1f925", alt: "Lying face", codepoint: "1f925" },
  "🤧": { name: "sneezing-face_1f927", alt: "Sneezing face", codepoint: "1f927" },
  "🤨": { name: "face-with-raised-eyebrow_1f928", alt: "Face with one eyebrow raised", codepoint: "1f928" },
  "🤩": { name: "star-struck_1f929", alt: "Grinning face with star eyes", codepoint: "1f929" },
  "🤪": { name: "zany-face_1f92a", alt: "Grinning face with one large and one small eye", codepoint: "1f92a" },
  "🤫": { name: "shushing-face_1f92b", alt: "Face with finger covering closed lips", codepoint: "1f92b" },
  "🤬": { name: "face-with-symbols-on-mouth_1f92c", alt: "Serious face with symbols covering mouth", codepoint: "1f92c" },
  "🤭": { name: "face-with-hand-over-mouth_1f92d", alt: "Smiling face with smiling eyes and hand covering mouth", codepoint: "1f92d" },
  "🤮": { name: "face-vomiting_1f92e", alt: "Face with open mouth vomiting", codepoint: "1f92e" },
  "🤯": { name: "exploding-head_1f92f", alt: "Shocked face with exploding head", codepoint: "1f92f" },
  "🥱": { name: "yawning-face_1f971", alt: "Yawning face", codepoint: "1f971" },
  "🥲": { name: "smiling-face-with-tear_1f972", alt: "Smiling face with tear", codepoint: "1f972" },
  "🥳": { name: "partying-face_1f973", alt: "Face with party horn and party hat", codepoint: "1f973" },
  "🥴": { name: "woozy-face_1f974", alt: "Face with uneven eyes and wavy mouth", codepoint: "1f974" },
  "🥵": { name: "hot-face_1f975", alt: "Overheated face", codepoint: "1f975" },
  "🥶": { name: "cold-face_1f976", alt: "Freezing face", codepoint: "1f976" },
  "🥸": { name: "disguised-face_1f978", alt: "Disguised face", codepoint: "1f978" },
  "🥹": { name: "face-holding-back-tears_1f979", alt: "Face holding back tears", codepoint: "1f979" },
  "🥺": { name: "pleading-face_1f97a", alt: "Face with pleading eyes", codepoint: "1f97a" },
  "🧐": { name: "face-with-monocle_1f9d0", alt: "Face with monocle", codepoint: "1f9d0" },
  "🧡": { name: "orange-heart_1f9e1", alt: "Orange heart", codepoint: "1f9e1" },
  "🩵": { name: "light-blue-heart_1fa75", alt: "Light blue heart", codepoint: "1fa75" },
  "🩶": { name: "grey-heart_1fa76", alt: "Grey heart", codepoint: "1fa76" },
  "🩷": { name: "pink-heart_1fa77", alt: "Pink heart", codepoint: "1fa77" },
  "🫠": { name: "melting-face_1fae0", alt: "Melting face", codepoint: "1fae0" },
  "🫡": { name: "saluting-face_1fae1", alt: "Saluting face", codepoint: "1fae1" },
  "🫢": { name: "face-with-open-eyes-and-hand-over-mouth_1fae2", alt: "Face with open eyes and hand over mouth", codepoint: "1fae2" },
  "🫣": { name: "face-with-peeking-eye_1fae3", alt: "Face with peeking eye", codepoint: "1fae3" },
  "🫤": { name: "face-with-diagonal-mouth_1fae4", alt: "Face with diagonal mouth", codepoint: "1fae4" },
  "🫥": { name: "dotted-line-face_1fae5", alt: "Dotted line face", codepoint: "1fae5" },
  "🫨": { name: "shaking-face_1fae8", alt: "Shaking face", codepoint: "1fae8" },

};
