/** CLDR naming exceptions in the pinned Fluent Emoji revision. */
export const fluentAssetNames: Record<string, readonly [folder: string, basename: string]> = {
  "1f311": ["New moon", "new_moon"],
  "1f312": ["Waxing crescent moon", "waxing_crescent_moon"],
  "1f313": ["First quarter moon", "first_quarter_moon"],
  "1f314": ["Waxing gibbous moon", "waxing_gibbous_moon"],
  "1f315": ["Full moon", "full_moon"],
  "1f316": ["Waning gibbous moon", "waning_gibbous_moon"],
  "1f317": ["Last quarter moon", "last_quarter_moon"],
  "1f318": ["Waning crescent moon", "waning_crescent_moon"],
  "1f3e0": ["House", "house"],
  "1f684": ["High-speed train", "high-speed_train"],
  "1f6a7": ["Construction", "construction"],
  "2b50": ["Star", "star"],
  "1f346": ["Eggplant", "eggplant"],
  "1f355": ["Pizza", "pizza"],
  "1f376": ["Sake", "sake"],
  "1f9c2": ["Salt", "salt"],
  "1f425": ["Front-facing baby chick", "front-facing_baby_chick"],
  "1f438": ["Frog", "frog"],
  "1f439": ["Hamster", "hamster"],
  "1f43a": ["Wolf", "wolf"],
  "1f43b": ["Bear", "bear"],
  "1f996": ["T-rex", "t-rex"],
  "1f383": ["Jack-o-lantern", "jack-o-lantern"],
  "1f387": ["Sparkler", "sparkler"],
  "1f3af": ["Bullseye", "bullseye"],
  "1f3be": ["Tennis", "tennis"],
  "1f3c0": ["Basketball", "basketball"],
  "1f52b": ["Water pistol", "water_pistol"],
  "1f94d": ["Lacrosse", "lacrosse"],
  "1f9e7": ["Red envelope", "red_envelope"],
  "1f9f5": ["Thread", "thread"],
  "1f9f6": ["Yarn", "yarn"],
  "1fa80": ["Yo-yo", "yo-yo"],
  "1fa85": ["Piñata", "piñata"],
  "1f455": ["T-shirt", "t-shirt"],
  "1f460": ["High-heeled shoe", "high-heeled_shoe"],
  "1f4c6": ["Tear-off calendar", "tear-off_calendar"],
  "1f4e2": ["Loudspeaker", "loudspeaker"],
  "1f4e7": ["E-mail", "e-mail"],
  "1f4e9": ["Envelope with arrow", "envelope_with_arrow"],
  "1f517": ["Link", "link"],
  "1f526": ["Flashlight", "flashlight"],
  "1f9ec": ["Dna", "dna"],
  "1f9fc": ["Soap", "soap"],
  "1fa71": ["One-piece swimsuit", "one-piece_swimsuit"],
  "1fa7b": ["X-ray", "x-ray"],
  "1f534": ["Red circle", "red_circle"],
  "1f535": ["Blue circle", "blue_circle"],
  "1f6ad": ["No smoking", "no_smoking"],
  "1f6b0": ["Potable water", "potable_water"],
  "1f6b1": ["Non-potable water", "non-potable_water"],
  "1f7e0": ["Orange circle", "orange_circle"],
  "1f7e1": ["Yellow circle", "yellow_circle"],
  "1f7e2": ["Green circle", "green_circle"],
  "1f7e3": ["Purple circle", "purple_circle"],
  "1f7e4": ["Brown circle", "brown_circle"],
  "1f7e5": ["Red square", "red_square"],
  "1f7e6": ["Blue square", "blue_square"],
  "1f7e7": ["Orange square", "orange_square"],
  "1f7e8": ["Yellow square", "yellow_square"],
  "1f7e9": ["Green square", "green_square"],
  "1f7ea": ["Purple square", "purple_square"],
  "1f7eb": ["Brown square", "brown_square"],
  "25fd": ["White medium-small square", "white_medium-small_square"],
  "25fe": ["Black medium-small square", "black_medium-small_square"],
  "26aa": ["White circle", "white_circle"],
  "26ab": ["Black circle", "black_circle"],
  "1f9de": ["Person genie", "person_genie"],
  "1f9df": ["Person zombie", "person_zombie"],
  "1f47d": ["Alien", "alien"],
  "1f4a4": ["Zzz", "zzz"],
  "1f4a5": ["Collision", "collision"],
  "1f4ab": ["Dizzy", "dizzy"],
  "1f635": ["Knocked-out face", "knocked-out_face"],
  "1f63d": ["Kissing cat", "kissing_cat"],
  "1f63e": ["Pouting cat", "pouting_cat"],
  "1f643": ["Upside-down face", "upside-down_face"],
  "1f648": ["See-no-evil monkey", "see-no-evil_monkey"],
  "1f649": ["Hear-no-evil monkey", "hear-no-evil_monkey"],
  "1f64a": ["Speak-no-evil monkey", "speak-no-evil_monkey"],
  "1f910": ["Zipper-mouth face", "zipper-mouth_face"],
  "1f911": ["Money-mouth face", "money-mouth_face"],
  "1f915": ["Face with head-bandage", "face_with_head-bandage"],
  "1f928": ["Face with raised eyebrow", "face_with_raised_eyebrow"],
  "1f929": ["Star-struck", "star-struck"],
  "1f92a": ["Zany face", "zany_face"],
  "1f92b": ["Shushing face", "shushing_face"],
  "1f92c": ["Face with symbols on mouth", "face_with_symbols_on_mouth"],
  "1f92d": ["Face with hand over mouth", "face_with_hand_over_mouth"],
  "1f92e": ["Face vomiting", "face_vomiting"],
  "1f92f": ["Exploding head", "exploding_head"],
  "1f973": ["Partying face", "partying_face"],
  "1f974": ["Woozy face", "woozy_face"],
  "1f975": ["Hot face", "hot_face"],
  "1f976": ["Cold face", "cold_face"],
  "1f97a": ["Pleading face", "pleading_face"],
};
