/**
 * Generated from microsoft/fluentui-emoji-animated metadata.
 * Source revision: daa0365c09795789ed2bc6e8b228c97736cb6669
 * Run: pnpm --filter emoji-styles-scripts generate:fluent-animated -- <checkout>
 */
export const fluentAnimatedAssetNames: Record<
  string,
  readonly [folder: string, basename: string, hasSkinTones: boolean]
> = {
  "1f6a1": ["Aerial tramway", "aerial_tramway", false],
  "2708": ["Airplane", "airplane", false],
  "1f6ec": ["Airplane arrival", "airplane_arrival", false],
  "1f6eb": ["Airplane departure", "airplane_departure", false],
  "23f0": ["Alarm clock", "alarm_clock", false],
  "1f47d": ["Alien", "alien", false],
  "1f47e": ["Alien monster", "alien_monster", false],
  "1f691": ["Ambulance", "ambulance", false],
  "1fac0": ["Anatomical heart", "anatomical_heart", false],
  "1f620": ["Angry face", "angry_face", false],
  "1f47f": ["Angry face with horns", "angry_face_with_horns", false],
  "1f627": ["Anguished face", "anguished_face", false],
  "1f41c": ["Ant", "ant", false],
  "1f630": ["Anxious face with sweat", "anxious_face_with_sweat", false],
  "1f69b": ["Articulated lorry", "articulated_lorry", false],
  "1f9d1-200d-1f3a8": ["Artist", "artist", true],
  "1f632": ["Astonished face", "astonished_face", false],
  "1f9d1-200d-1f680": ["Astronaut", "astronaut", true],
  "1f6fa": ["Auto rickshaw", "auto_rickshaw", false],
  "1f697": ["Automobile", "automobile", false],
  "1f476": ["Baby", "baby", true],
  "1f47c": ["Baby angel", "baby_angel", true],
  "1f424": ["Baby chick", "baby_chick", false],
  "1f447": ["Backhand index pointing down", "backhand_index_pointing_down", true],
  "1f448": ["Backhand index pointing left", "backhand_index_pointing_left", true],
  "1f449": ["Backhand index pointing right", "backhand_index_pointing_right", true],
  "1f446": ["Backhand index pointing up", "backhand_index_pointing_up", true],
  "1f9a1": ["Badger", "badger", false],
  "1f488": ["Barber pole", "barber_pole", false],
  "1f987": ["Bat", "bat", false],
  "1f601": ["Beaming face with smiling eyes", "beaming_face_with_smiling_eyes", false],
  "1f43b": ["Bear", "bear", false],
  "1f493": ["Beating heart", "beating_heart", false],
  "1f9ab": ["Beaver", "beaver", false],
  "1f37a": ["Beer mug", "beer_mug", false],
  "1fab2": ["Beetle", "beetle", false],
  "1f426": ["Bird", "bird", false],
  "1f382": ["Birthday cake", "birthday_cake", false],
  "1f9ac": ["Bison", "bison", false],
  "1f426-200d-2b1b": ["Black bird", "black_bird", false],
  "1f408-200d-2b1b": ["Black cat", "black_cat", false],
  "1f3f4": ["Black flag", "black_flag", false],
  "1f5a4": ["Black heart", "black_heart", false],
  "1f421": ["Blowfish", "blowfish", false],
  "1f499": ["Blue heart", "blue_heart", false],
  "1f417": ["Boar", "boar", false],
  "1f4a3": ["Bomb", "bomb", false],
  "1f9b4": ["Bone", "bone", false],
  "1f37e": ["Bottle with popping cork", "bottle_with_popping_cork", false],
  "1f466": ["Boy", "boy", true],
  "1f9e0": ["Brain", "brain", false],
  "1f931": ["Breast feeding", "breast_feeding", true],
  "1f494": ["Broken heart", "broken_heart", false],
  "1f90e": ["Brown heart", "brown_heart", false],
  "1f41b": ["Bug", "bug", false],
  "1f68c": ["Bus", "bus", false],
  "1f464": ["Bust in silhouette", "bust_in_silhouette", false],
  "1f465": ["Busts in silhouette", "busts_in_silhouette", false],
  "1f98b": ["Butterfly", "butterfly", false],
  "1f919": ["Call me hand", "call_me_hand", true],
  "1f42a": ["Camel", "camel", false],
  "1f4f8": ["Camera with flash", "camera_with_flash", false],
  "1f6f6": ["Canoe", "canoe", false],
  "1f408": ["Cat", "cat", false],
  "1f431": ["Cat face", "cat_face", false],
  "1f639": ["Cat with tears of joy", "cat_with_tears_of_joy", false],
  "1f63c": ["Cat with wry smile", "cat_with_wry_smile", false],
  "1f3c1": ["Chequered flag", "chequered_flag", false],
  "1f414": ["Chicken", "chicken", false],
  "1f9d2": ["Child", "child", true],
  "1f43f": ["Chipmunk", "chipmunk", false],
  "1f384": ["Christmas tree", "christmas_tree", false],
  "1f44f": ["Clapping hands", "clapping_hands", true],
  "1f37b": ["Clinking beer mugs", "clinking_beer_mugs", false],
  "1f942": ["Clinking glasses", "clinking_glasses", false],
  "1f302": ["Closed umbrella", "closed_umbrella", false],
  "2601": ["Cloud", "cloud", false],
  "1f329": ["Cloud with lightning", "cloud_with_lightning", false],
  "26c8": ["Cloud with lightning and rain", "cloud_with_lightning_and_rain", false],
  "1f327": ["Cloud with rain", "cloud_with_rain", false],
  "1f328": ["Cloud with snow", "cloud_with_snow", false],
  "1f921": ["Clown face", "clown_face", false],
  "1fab3": ["Cockroach", "cockroach", false],
  "1f378": ["Cocktail glass", "cocktail_glass", false],
  "1f976": ["Cold face", "cold_face", false],
  "2604": ["Comet", "comet", false],
  "1f9ed": ["Compass", "compass", false],
  "1f616": ["Confounded face", "confounded_face", false],
  "1f615": ["Confused face", "confused_face", false],
  "1f477": ["Construction worker", "construction_worker", true],
  "1f9d1-200d-1f373": ["Cook", "cook", true],
  "1f404": ["Cow", "cow", false],
  "1f42e": ["Cow face", "cow_face", false],
  "1f920": ["Cowboy hat face", "cowboy_hat_face", false],
  "1f980": ["Crab", "crab", false],
  "1f997": ["Cricket", "cricket", false],
  "1f40a": ["Crocodile", "crocodile", false],
  "1f91e": ["Crossed fingers", "crossed_fingers", true],
  "1f38c": ["Crossed flags", "crossed_flags", false],
  "1f63f": ["Crying cat", "crying_cat", false],
  "1f622": ["Crying face", "crying_face", false],
  "1f52e": ["Crystal ball", "crystal_ball", false],
  "1f300": ["Cyclone", "cyclone", false],
  "1f98c": ["Deer", "deer", false],
  "1f69a": ["Delivery truck", "delivery_truck", false],
  "1f575": ["Detective", "detective", true],
  "1f61e": ["Disappointed face", "disappointed_face", false],
  "1f978": ["Disguised face", "disguised_face", false],
  "1f9a4": ["Dodo", "dodo", false],
  "1f415": ["Dog", "dog", false],
  "1f436": ["Dog face", "dog_face", false],
  "1f42c": ["Dolphin", "dolphin", false],
  "1facf": ["Donkey", "donkey", false],
  "1f54a": ["Dove", "dove", false],
  "1f613": ["Downcast face with sweat", "downcast_face_with_sweat", false],
  "1f409": ["Dragon", "dragon", false],
  "1f432": ["Dragon face", "dragon_face", false],
  "1f924": ["Drooling face", "drooling_face", false],
  "1f4a7": ["Droplet", "droplet", false],
  "1f986": ["Duck", "duck", false],
  "1f985": ["Eagle", "eagle", false],
  "1f442": ["Ear", "ear", true],
  "1f9bb": ["Ear with hearing aid", "ear_with_hearing_aid", true],
  "1f557": ["Eight oclock", "eight_oclock", false],
  "1f563": ["Eight-thirty", "eight-thirty", false],
  "1f418": ["Elephant", "elephant", false],
  "1f55a": ["Eleven oclock", "eleven_oclock", false],
  "1f566": ["Eleven-thirty", "eleven-thirty", false],
  "1f411": ["Ewe", "ewe", false],
  "1f92f": ["Exploding head", "exploding_head", false],
  "1f441": ["Eye", "eye", false],
  "1f440": ["Eyes", "eyes", false],
  "1f618": ["Face blowing a kiss", "face_blowing_a_kiss", false],
  "1f62e-200d-1f4a8": ["Face exhaling", "face_exhaling", false],
  "1f979": ["Face holding back tears", "face_holding_back_tears", false],
  "1f636-200d-1f32b": ["Face in clouds", "face_in_clouds", false],
  "1f60b": ["Face savoring food", "face_savoring_food", false],
  "1f631": ["Face screaming in fear", "face_screaming_in_fear", false],
  "1f92e": ["Face vomiting", "face_vomiting", false],
  "1f92d": ["Face with hand over mouth", "face_with_hand_over_mouth", false],
  "1f915": ["Face with head-bandage", "face_with_head-bandage", false],
  "1f637": ["Face with medical mask", "face_with_medical_mask", false],
  "1f9d0": ["Face with monocle", "face_with_monocle", false],
  "1fae2": ["Face with open eyes and hand over mouth", "face_with_open_eyes_and_hand_over_mouth", false],
  "1f62e": ["Face with open mouth", "face_with_open_mouth", false],
  "1f928": ["Face with raised eyebrow", "face_with_raised_eyebrow", false],
  "1f644": ["Face with rolling eyes", "face_with_rolling_eyes", false],
  "1f635-200d-1f4ab": ["Face with spiral eyes", "face_with_spiral_eyes", false],
  "1f624": ["Face with steam from nose", "face_with_steam_from_nose", false],
  "1f92c": ["Face with symbols on mouth", "face_with_symbols_on_mouth", false],
  "1f602": ["Face with tears of joy", "face_with_tears_of_joy", false],
  "1f912": ["Face with thermometer", "face_with_thermometer", false],
  "1f61b": ["Face with tongue", "face_with_tongue", false],
  "1f636": ["Face without mouth", "face_without_mouth", false],
  "1f9d1-200d-1f3ed": ["Factory worker", "factory_worker", true],
  "1f9d1-200d-1f33e": ["Farmer", "farmer", true],
  "1f628": ["Fearful face", "fearful_face", false],
  "1f3a1": ["Ferris wheel", "ferris_wheel", false],
  "26f4": ["Ferry", "ferry", false],
  "1f525": ["Fire", "fire", false],
  "1f692": ["Fire engine", "fire_engine", false],
  "1f9d1-200d-1f692": ["Firefighter", "firefighter", true],
  "1f31b": ["First quarter moon face", "first_quarter_moon_face", false],
  "1f41f": ["Fish", "fish", false],
  "1f554": ["Five oclock", "five_oclock", false],
  "1f560": ["Five-thirty", "five-thirty", false],
  "1f9a9": ["Flamingo", "flamingo", false],
  "1f4aa": ["Flexed biceps", "flexed_biceps", true],
  "1f633": ["Flushed face", "flushed_face", false],
  "1fab0": ["Fly", "fly", false],
  "1f6f8": ["Flying saucer", "flying_saucer", false],
  "1f32b": ["Fog", "fog", false],
  "1f64f": ["Folded hands", "folded_hands", true],
  "1f9b6": ["Foot", "foot", true],
  "1f463": ["Footprints", "footprints", false],
  "26f2": ["Fountain", "fountain", false],
  "1f553": ["Four oclock", "four_oclock", false],
  "1f55f": ["Four-thirty", "four-thirty", false],
  "1f98a": ["Fox", "fox", false],
  "1f438": ["Frog", "frog", false],
  "1f425": ["Front-facing baby chick", "front-facing_baby_chick", false],
  "2639": ["Frowning face", "frowning_face", false],
  "1f626": ["Frowning face with open mouth", "frowning_face_with_open_mouth", false],
  "1f31d": ["Full moon face", "full_moon_face", false],
  "1f47b": ["Ghost", "ghost", false],
  "1f992": ["Giraffe", "giraffe", false],
  "1f467": ["Girl", "girl", true],
  "1f31f": ["Glowing star", "glowing_star", false],
  "1f410": ["Goat", "goat", false],
  "1f47a": ["Goblin", "goblin", false],
  "1fabf": ["Goose", "goose", false],
  "1f98d": ["Gorilla", "gorilla", false],
  "1f49a": ["Green heart", "green_heart", false],
  "1fa76": ["Grey heart", "grey_heart", false],
  "1f62c": ["Grimacing face", "grimacing_face", false],
  "1f63a": ["Grinning cat", "grinning_cat", false],
  "1f638": ["Grinning cat with smiling eyes", "grinning_cat_with_smiling_eyes", false],
  "1f600": ["Grinning face", "grinning_face", false],
  "1f603": ["Grinning face with big eyes", "grinning_face_with_big_eyes", false],
  "1f604": ["Grinning face with smiling eyes", "grinning_face_with_smiling_eyes", false],
  "1f605": ["Grinning face with sweat", "grinning_face_with_sweat", false],
  "1f606": ["Grinning squinting face", "grinning_squinting_face", false],
  "1f497": ["Growing heart", "growing_heart", false],
  "1f482": ["Guard", "guard", true],
  "1f9ae": ["Guide dog", "guide_dog", false],
  "1f439": ["Hamster", "hamster", false],
  "1f590": ["Hand with fingers splayed", "hand_with_fingers_splayed", true],
  "1faf0": ["Hand with index finger and thumb crossed", "hand_with_index_finger_and_thumb_crossed", true],
  "1f91d": ["Handshake", "handshake", true],
  "1f423": ["Hatching chick", "hatching_chick", false],
  "1f642-200d-2194": ["Head shaking horizontally", "head_shaking_horizontally", false],
  "1f642-200d-2195": ["Head shaking vertically", "head_shaking_vertically", false],
  "1f9d1-200d-2695": ["Health worker", "health_worker", true],
  "1f649": ["Hear-no-evil monkey", "hear-no-evil_monkey", false],
  "1f49f": ["Heart decoration", "heart_decoration", false],
  "2763": ["Heart exclamation", "heart_exclamation", false],
  "1faf6": ["Heart hands", "heart_hands", true],
  "2764-200d-1f525": ["Heart on fire", "heart_on_fire", false],
  "1f498": ["Heart with arrow", "heart_with_arrow", false],
  "1f49d": ["Heart with ribbon", "heart_with_ribbon", false],
  "1f994": ["Hedgehog", "hedgehog", false],
  "1f681": ["Helicopter", "helicopter", false],
  "26a1": ["High voltage", "high_voltage", false],
  "1f99b": ["Hippopotamus", "hippopotamus", false],
  "1f41d": ["Honeybee", "honeybee", false],
  "1f40e": ["Horse", "horse", false],
  "1f434": ["Horse face", "horse_face", false],
  "1f3c7": ["Horse racing", "horse_racing", true],
  "2615": ["Hot beverage", "hot_beverage", false],
  "1f975": ["Hot face", "hot_face", false],
  "231b": ["Hourglass done", "hourglass_done", false],
  "23f3": ["Hourglass not done", "hourglass_not_done", false],
  "1f917": ["Hugging face", "hugging_face", false],
  "1f4af": ["Hundred points", "hundred_points", false],
  "1f62f": ["Hushed face", "hushed_face", false],
  "1f6d6": ["Hut", "hut", false],
  "1faf5": ["Index pointing at the viewer", "index_pointing_at_the_viewer", true],
  "261d": ["Index pointing up", "index_pointing_up", true],
  "1f383": ["Jack-o-lantern", "jack-o-lantern", false],
  "1fabc": ["Jellyfish", "jellyfish", false],
  "1f9d1-200d-2696": ["Judge", "judge", true],
  "1f998": ["Kangaroo", "kangaroo", false],
  "1f63d": ["Kissing cat", "kissing_cat", false],
  "1f617": ["Kissing face", "kissing_face", false],
  "1f61a": ["Kissing face with closed eyes", "kissing_face_with_closed_eyes", false],
  "1f619": ["Kissing face with smiling eyes", "kissing_face_with_smiling_eyes", false],
  "1f635": ["Knocked-out face", "knocked-out_face", false],
  "1f428": ["Koala", "koala", false],
  "1f41e": ["Lady beetle", "lady_beetle", false],
  "1f31c": ["Last quarter moon face", "last_quarter_moon_face", false],
  "1f343": ["Leaf fluttering in wind", "leaf_fluttering_in_wind", false],
  "1f91b": ["Left-facing fist", "left-facing_fist", true],
  "1faf2": ["Leftwards hand", "leftwards_hand", true],
  "1faf7": ["Leftwards pushing hand", "leftwards_pushing_hand", true],
  "1f9b5": ["Leg", "leg", true],
  "1f406": ["Leopard", "leopard", false],
  "1fa75": ["Light blue heart", "light_blue_heart", false],
  "1f688": ["Light rail", "light_rail", false],
  "1f981": ["Lion", "lion", false],
  "1f98e": ["Lizard", "lizard", false],
  "1f999": ["Llama", "llama", false],
  "1f99e": ["Lobster", "lobster", false],
  "1f682": ["Locomotive", "locomotive", false],
  "1f62d": ["Loudly crying face", "loudly_crying_face", false],
  "1f48c": ["Love letter", "love_letter", false],
  "1f91f": ["Love-you gesture", "love-you_gesture", true],
  "1fac1": ["Lungs", "lungs", false],
  "1f925": ["Lying face", "lying_face", false],
  "1f9a3": ["Mammoth", "mammoth", false],
  "1f468": ["Man", "man", true],
  "1f468-200d-1f3a8": ["Man artist", "man_artist", true],
  "1f468-200d-1f680": ["Man astronaut", "man_astronaut", true],
  "1f468-200d-1f9b2": ["Man bald", "man_bald", true],
  "1f9d4-200d-2642": ["Man beard", "man_beard", true],
  "1f6b4-200d-2642": ["Man biking", "man_biking", true],
  "1f471-200d-2642": ["Man blonde hair", "man_blonde_hair", true],
  "26f9-200d-2642": ["Man bouncing ball", "man_bouncing_ball", true],
  "1f647-200d-2642": ["Man bowing", "man_bowing", true],
  "1f938-200d-2642": ["Man cartwheeling", "man_cartwheeling", true],
  "1f9d7-200d-2642": ["Man climbing", "man_climbing", true],
  "1f477-200d-2642": ["Man construction worker", "man_construction_worker", true],
  "1f468-200d-1f373": ["Man cook", "man_cook", true],
  "1f468-200d-1f9b1": ["Man curly hair", "man_curly_hair", true],
  "1f57a": ["Man dancing", "man_dancing", true],
  "1f575-200d-2642": ["Man detective", "man_detective", true],
  "1f9dd-200d-2642": ["Man elf", "man_elf", true],
  "1f926-200d-2642": ["Man facepalming", "man_facepalming", true],
  "1f468-200d-1f3ed": ["Man factory worker", "man_factory_worker", true],
  "1f9da-200d-2642": ["Man fairy", "man_fairy", true],
  "1f468-200d-1f33e": ["Man farmer", "man_farmer", true],
  "1f468-200d-1f37c": ["Man feeding baby", "man_feeding_baby", true],
  "1f468-200d-1f692": ["Man firefighter", "man_firefighter", true],
  "1f64d-200d-2642": ["Man frowning", "man_frowning", true],
  "1f9de-200d-2642": ["Man genie", "man_genie", false],
  "1f645-200d-2642": ["Man gesturing no", "man_gesturing_no", true],
  "1f646-200d-2642": ["Man gesturing ok", "man_gesturing_ok", true],
  "1f487-200d-2642": ["Man getting haircut", "man_getting_haircut", true],
  "1f486-200d-2642": ["Man getting massage", "man_getting_massage", true],
  "1f3cc-200d-2642": ["Man golfing", "man_golfing", true],
  "1f482-200d-2642": ["Man guard", "man_guard", true],
  "1f468-200d-2695": ["Man health worker", "man_health_worker", true],
  "1f9d8-200d-2642": ["Man in lotus position", "man_in_lotus_position", true],
  "1f468-200d-1f9bd": ["Man in manual wheelchair", "man_in_manual_wheelchair", true],
  "1f468-200d-1f9bd-200d-27a1": ["Man in manual wheelchair facing right", "man_in_manual_wheelchair_facing_right", true],
  "1f468-200d-1f9bc": ["Man in motorized wheelchair", "man_in_motorized_wheelchair", true],
  "1f468-200d-1f9bc-200d-27a1": ["Man in motorized wheelchair facing right", "man_in_motorized_wheelchair_facing_right", true],
  "1f9d6-200d-2642": ["Man in steamy room", "man_in_steamy_room", true],
  "1f935-200d-2642": ["Man in tuxedo", "man_in_tuxedo", true],
  "1f468-200d-2696": ["Man judge", "man_judge", true],
  "1f939-200d-2642": ["Man juggling", "man_juggling", true],
  "1f3cb-200d-2642": ["Man lifting weights", "man_lifting_weights", true],
  "1f9d9-200d-2642": ["Man mage", "man_mage", true],
  "1f468-200d-1f527": ["Man mechanic", "man_mechanic", true],
  "1f9dc-200d-2642": ["Man merpeople", "man_merpeople", true],
  "1f6b5-200d-2642": ["Man mountain biking", "man_mountain_biking", true],
  "1f468-200d-1f4bc": ["Man office worker", "man_office_worker", true],
  "1f468-200d-2708": ["Man pilot", "man_pilot", true],
  "1f93e-200d-2642": ["Man playing handball", "man_playing_handball", true],
  "1f93d-200d-2642": ["Man playing water polo", "man_playing_water_polo", true],
  "1f46e-200d-2642": ["Man police officer", "man_police_officer", true],
  "1f64e-200d-2642": ["Man pouting", "man_pouting", true],
  "1f64b-200d-2642": ["Man raising hand", "man_raising_hand", true],
  "1f468-200d-1f9b0": ["Man red hair", "man_red_hair", true],
  "1f6a3-200d-2642": ["Man rowing boat", "man_rowing_boat", true],
  "1f3c3-200d-2642": ["Man running", "man_running", true],
  "1f3c3-200d-2642-200d-27a1": ["Man running facing right", "man_running_facing_right", true],
  "1f468-200d-1f52c": ["Man scientist", "man_scientist", true],
  "1f937-200d-2642": ["Man shrugging", "man_shrugging", true],
  "1f468-200d-1f3a4": ["Man singer", "man_singer", true],
  "1f9cd-200d-2642": ["Man standing", "man_standing", true],
  "1f468-200d-1f393": ["Man student", "man_student", true],
  "1f9b8-200d-2642": ["Man superhero", "man_superhero", true],
  "1f9b9-200d-2642": ["Man supervillain", "man_supervillain", true],
  "1f3c4-200d-2642": ["Man surfing", "man_surfing", true],
  "1f3ca-200d-2642": ["Man swimming", "man_swimming", true],
  "1f468-200d-1f3eb": ["Man teacher", "man_teacher", true],
  "1f481-200d-2642": ["Man tipping hand", "man_tipping_hand", true],
  "1f9db-200d-2642": ["Man vampire", "man_vampire", true],
  "1f6b6-200d-2642": ["Man walking", "man_walking", true],
  "1f6b6-200d-2642-200d-27a1": ["Man walking facing right", "man_walking_facing_right", true],
  "1f473-200d-2642": ["Man wearing turban", "man_wearing_turban", true],
  "1f468-200d-1f9b3": ["Man white hair", "man_white_hair", true],
  "1f46f-200d-2642": ["Man with bunny ears", "man_with_bunny_ears", true],
  "1f470-200d-2642": ["Man with veil", "man_with_veil", true],
  "1f468-200d-1f9af": ["Man with white cane", "man_with_white_cane", true],
  "1f468-200d-1f9af-200d-27a1": ["Man with white cane facing right", "man_with_white_cane_facing_right", true],
  "1f93c-200d-2642": ["Man wrestling", "man_wrestling", true],
  "1f9df-200d-2642": ["Man zombie", "man_zombie", false],
  "1f570": ["Mantelpiece clock", "mantelpiece_clock", false],
  "1fa87": ["Maracas", "maracas", false],
  "1f9d1-200d-1f527": ["Mechanic", "mechanic", true],
  "1f9be": ["Mechanical arm", "mechanical_arm", false],
  "1f9bf": ["Mechanical leg", "mechanical_leg", false],
  "1fae0": ["Melting face", "melting_face", false],
  "2764-200d-1fa79": ["Mending heart", "mending_heart", false],
  "1f9a0": ["Microbe", "microbe", false],
  "1f595": ["Middle finger", "middle_finger", true],
  "1f30c": ["Milky way", "milky_way", false],
  "1f690": ["Minibus", "minibus", false],
  "1f911": ["Money-mouth face", "money-mouth_face", false],
  "1f412": ["Monkey", "monkey", false],
  "1f435": ["Monkey face", "monkey_face", false],
  "1f69d": ["Monorail", "monorail", false],
  "1face": ["Moose", "moose", false],
  "1f99f": ["Mosquito", "mosquito", false],
  "1f6e5": ["Motor boat", "motor_boat", false],
  "1f3cd": ["Motorcycle", "motorcycle", false],
  "1f6a0": ["Mountain cableway", "mountain_cableway", false],
  "1f401": ["Mouse", "mouse", false],
  "1f42d": ["Mouse face", "mouse_face", false],
  "1f444": ["Mouth", "mouth", false],
  "1f936": ["Mrs claus", "mrs_claus", true],
  "1f3b6": ["Musical notes", "musical_notes", false],
  "1f9d1-200d-1f384": ["Mx claus", "mx_claus", true],
  "1f485": ["Nail polish", "nail_polish", true],
  "1f922": ["Nauseated face", "nauseated_face", false],
  "1f913": ["Nerd face", "nerd_face", false],
  "1f610": ["Neutral face", "neutral_face", false],
  "1f31a": ["New moon face", "new_moon_face", false],
  "1f558": ["Nine oclock", "nine_oclock", false],
  "1f564": ["Nine-thirty", "nine-thirty", false],
  "1f977": ["Ninja", "ninja", true],
  "1f443": ["Nose", "nose", true],
  "1f419": ["Octopus", "octopus", false],
  "1f9d1-200d-1f4bc": ["Office worker", "office_worker", true],
  "1f479": ["Ogre", "ogre", false],
  "1f44c": ["Ok hand", "ok_hand", true],
  "1f474": ["Old man", "old_man", true],
  "1f475": ["Old woman", "old_woman", true],
  "1f9d3": ["Older person", "older_person", true],
  "1f698": ["Oncoming automobile", "oncoming_automobile", false],
  "1f44a": ["Oncoming fist", "oncoming_fist", true],
  "1f694": ["Oncoming police car", "oncoming_police_car", false],
  "1f696": ["Oncoming taxi", "oncoming_taxi", false],
  "1f550": ["One oclock", "one_oclock", false],
  "1f55c": ["One-thirty", "one-thirty", false],
  "1f450": ["Open hands", "open_hands", true],
  "1f9e1": ["Orange heart", "orange_heart", false],
  "1f9a7": ["Orangutan", "orangutan", false],
  "1f9a6": ["Otter", "otter", false],
  "1f989": ["Owl", "owl", false],
  "1f402": ["Ox", "ox", false],
  "1faf3": ["Palm down hand", "palm_down_hand", true],
  "1faf4": ["Palm up hand", "palm_up_hand", true],
  "1f932": ["Palms up together", "palms_up_together", true],
  "1f43c": ["Panda", "panda", false],
  "1fa82": ["Parachute", "parachute", false],
  "1f99c": ["Parrot", "parrot", false],
  "1f389": ["Party popper", "party_popper", false],
  "1f973": ["Partying face", "partying_face", false],
  "1f6f3": ["Passenger ship", "passenger_ship", false],
  "1f43e": ["Paw prints", "paw_prints", false],
  "1f99a": ["Peacock", "peacock", false],
  "1f427": ["Penguin", "penguin", false],
  "1f614": ["Pensive face", "pensive_face", false],
  "1fac2": ["People hugging", "people_hugging", false],
  "1f623": ["Persevering face", "persevering_face", false],
  "1f9d1": ["Person", "person", true],
  "1f9d1-200d-1f9b2": ["Person bald", "person_bald", true],
  "1f9d4": ["Person beard", "person_beard", true],
  "1f6b4": ["Person biking", "person_biking", true],
  "1f471": ["Person blonde hair", "person_blonde_hair", true],
  "26f9": ["Person bouncing ball", "person_bouncing_ball", true],
  "1f647": ["Person bowing", "person_bowing", true],
  "1f938": ["Person cartwheeling", "person_cartwheeling", true],
  "1f9d7": ["Person climbing", "person_climbing", true],
  "1f9d1-200d-1f9b1": ["Person curly hair", "person_curly_hair", true],
  "1f9dd": ["Person elf", "person_elf", true],
  "1f926": ["Person facepalming", "person_facepalming", true],
  "1f9da": ["Person fairy", "person_fairy", true],
  "1f9d1-200d-1f37c": ["Person feeding baby", "person_feeding_baby", true],
  "1f93a": ["Person fencing", "person_fencing", false],
  "1f64d": ["Person frowning", "person_frowning", true],
  "1f9de": ["Person genie", "person_genie", true],
  "1f645": ["Person gesturing no", "person_gesturing_no", true],
  "1f646": ["Person gesturing ok", "person_gesturing_ok", true],
  "1f487": ["Person getting haircut", "person_getting_haircut", true],
  "1f486": ["Person getting massage", "person_getting_massage", true],
  "1f3cc": ["Person golfing", "person_golfing", true],
  "1f6cc": ["Person in bed", "person_in_bed", true],
  "1f9d8": ["Person in lotus position", "person_in_lotus_position", true],
  "1f9d1-200d-1f9bd": ["Person in manual wheelchair", "person_in_manual_wheelchair", true],
  "1f9d1-200d-1f9bd-200d-27a1": ["Person in manual wheelchair facing right", "person_in_manual_wheelchair_facing_right", true],
  "1f9d1-200d-1f9bc": ["Person in motorized wheelchair", "person_in_motorized_wheelchair", true],
  "1f9d1-200d-1f9bc-200d-27a1": ["Person in motorized wheelchair facing right", "person_in_motorized_wheelchair_facing_right", true],
  "1f9d6": ["Person in steamy room", "person_in_steamy_room", true],
  "1f574": ["Person in suit levitating", "person_in_suit_levitating", true],
  "1f935": ["Person in tuxedo", "person_in_tuxedo", true],
  "1f939": ["Person juggling", "person_juggling", true],
  "1f3cb": ["Person lifting weights", "person_lifting_weights", true],
  "1f9d9": ["Person mage", "person_mage", true],
  "1f9dc": ["Person merpeople", "person_merpeople", true],
  "1f6b5": ["Person mountain biking", "person_mountain_biking", true],
  "1f93e": ["Person playing handball", "person_playing_handball", true],
  "1f64e": ["Person pouting", "person_pouting", true],
  "1f64b": ["Person raising hand", "person_raising_hand", true],
  "1f9d1-200d-1f9b0": ["Person red hair", "person_red_hair", true],
  "1f6a3": ["Person rowing boat", "person_rowing_boat", true],
  "1f3c3": ["Person running", "person_running", true],
  "1f3c3-200d-27a1": ["Person running facing right", "person_running_facing_right", true],
  "1f937": ["Person shrugging", "person_shrugging", true],
  "1f9cd": ["Person standing", "person_standing", true],
  "1f9b8": ["Person superhero", "person_superhero", true],
  "1f9b9": ["Person supervillain", "person_supervillain", true],
  "1f3c4": ["Person surfing", "person_surfing", true],
  "1f3ca": ["Person swimming", "person_swimming", true],
  "1f6c0": ["Person taking bath", "person_taking_bath", true],
  "1f481": ["Person tipping hand", "person_tipping_hand", true],
  "1f9db": ["Person vampire", "person_vampire", true],
  "1f6b6": ["Person walking", "person_walking", true],
  "1f6b6-200d-27a1": ["Person walking facing right", "person_walking_facing_right", true],
  "1f473": ["Person wearing turban", "person_wearing_turban", true],
  "1f9d1-200d-1f9b3": ["Person white hair", "person_white_hair", true],
  "1f46f": ["Person with bunny ears", "person_with_bunny_ears", true],
  "1fac5": ["Person with crown", "person_with_crown", true],
  "1f472": ["Person with skullcap", "person_with_skullcap", true],
  "1f470": ["Person with veil", "person_with_veil", true],
  "1f9d1-200d-1f9af": ["Person with white cane", "person_with_white_cane", true],
  "1f9d1-200d-1f9af-200d-27a1": ["Person with white cane facing right", "person_with_white_cane_facing_right", true],
  "1f93c": ["Person wrestling", "person_wrestling", true],
  "1f9df": ["Person zombie", "person_zombie", false],
  "1f426-200d-1f525": ["Phoenix", "phoenix", false],
  "1f416": ["Pig", "pig", false],
  "1f437": ["Pig face", "pig_face", false],
  "1f43d": ["Pig nose", "pig_nose", false],
  "1f4a9": ["Pile of poo", "pile_of_poo", false],
  "1f9d1-200d-2708": ["Pilot", "pilot", true],
  "1f90c": ["Pinched fingers", "pinched_fingers", true],
  "1f90f": ["Pinching hand", "pinching_hand", true],
  "1fa77": ["Pink heart", "pink_heart", false],
  "1f3f4-200d-2620": ["Pirate flag", "pirate_flag", false],
  "1f97a": ["Pleading face", "pleading_face", false],
  "1f43b-200d-2744": ["Polar bear", "polar_bear", false],
  "1f693": ["Police car", "police_car", false],
  "1f46e": ["Police officer", "police_officer", true],
  "1f429": ["Poodle", "poodle", false],
  "1f621": ["Pouting face", "pouting_face", false],
  "1fac3": ["Pregnant man", "pregnant_man", true],
  "1fac4": ["Pregnant person", "pregnant_person", true],
  "1f930": ["Pregnant woman", "pregnant_woman", true],
  "1f934": ["Prince", "prince", true],
  "1f478": ["Princess", "princess", true],
  "1f49c": ["Purple heart", "purple_heart", false],
  "1f407": ["Rabbit", "rabbit", false],
  "1f430": ["Rabbit face", "rabbit_face", false],
  "1f99d": ["Raccoon", "raccoon", false],
  "1f3ce": ["Racing car", "racing_car", false],
  "1f308": ["Rainbow", "rainbow", false],
  "1f3f3-200d-1f308": ["Rainbow flag", "rainbow_flag", false],
  "1f91a": ["Raised back of hand", "raised_back_of_hand", true],
  "270a": ["Raised fist", "raised_fist", true],
  "270b": ["Raised hand", "raised_hand", true],
  "1f64c": ["Raising hands", "raising_hands", true],
  "1f40f": ["Ram", "ram", false],
  "1f400": ["Rat", "rat", false],
  "2764": ["Red heart", "red_heart", false],
  "1f60c": ["Relieved face", "relieved_face", false],
  "1f49e": ["Revolving hearts", "revolving_hearts", false],
  "1f98f": ["Rhinoceros", "rhinoceros", false],
  "1f91c": ["Right-facing fist", "right-facing_fist", true],
  "1faf1": ["Rightwards hand", "rightwards_hand", true],
  "1faf8": ["Rightwards pushing hand", "rightwards_pushing_hand", true],
  "1fa90": ["Ringed planet", "ringed_planet", false],
  "1f916": ["Robot", "robot", false],
  "1f680": ["Rocket", "rocket", false],
  "1f3a2": ["Roller coaster", "roller_coaster", false],
  "1f6fc": ["Roller skate", "roller_skate", false],
  "1f923": ["Rolling on the floor laughing", "rolling_on_the_floor_laughing", false],
  "1f413": ["Rooster", "rooster", false],
  "1f625": ["Sad but relieved face", "sad_but_relieved_face", false],
  "26f5": ["Sailboat", "sailboat", false],
  "1f385": ["Santa claus", "santa_claus", true],
  "1f995": ["Sauropod", "sauropod", false],
  "1f9d1-200d-1f52c": ["Scientist", "scientist", true],
  "1f982": ["Scorpion", "scorpion", false],
  "1f9ad": ["Seal", "seal", false],
  "1f4ba": ["Seat", "seat", false],
  "1f648": ["See-no-evil monkey", "see-no-evil_monkey", false],
  "1f933": ["Selfie", "selfie", true],
  "1f415-200d-1f9ba": ["Service dog", "service_dog", false],
  "1f556": ["Seven oclock", "seven_oclock", false],
  "1f562": ["Seven-thirty", "seven-thirty", false],
  "1fae8": ["Shaking face", "shaking_face", false],
  "1f988": ["Shark", "shark", false],
  "1f6a2": ["Ship", "ship", false],
  "1f320": ["Shooting star", "shooting_star", false],
  "1f990": ["Shrimp", "shrimp", false],
  "1f92b": ["Shushing face", "shushing_face", false],
  "1f918": ["Sign of the horns", "sign_of_the_horns", true],
  "1f9d1-200d-1f3a4": ["Singer", "singer", true],
  "1f555": ["Six oclock", "six_oclock", false],
  "1f561": ["Six-thirty", "six-thirty", false],
  "26f7": ["Skier", "skier", true],
  "1f480": ["Skull", "skull", false],
  "2620": ["Skull and crossbones", "skull_and_crossbones", false],
  "1f9a8": ["Skunk", "skunk", false],
  "1f634": ["Sleeping face", "sleeping_face", false],
  "1f62a": ["Sleepy face", "sleepy_face", false],
  "1f641": ["Slightly frowning face", "slightly_frowning_face", false],
  "1f642": ["Slightly smiling face", "slightly_smiling_face", false],
  "1f9a5": ["Sloth", "sloth", false],
  "1f6e9": ["Small airplane", "small_airplane", false],
  "1f63b": ["Smiling cat with heart-eyes", "smiling_cat_with_heart-eyes", false],
  "263a": ["Smiling face", "smiling_face", false],
  "1f607": ["Smiling face with halo", "smiling_face_with_halo", false],
  "1f60d": ["Smiling face with heart-eyes", "smiling_face_with_heart-eyes", false],
  "1f970": ["Smiling face with hearts", "smiling_face_with_hearts", false],
  "1f608": ["Smiling face with horns", "smiling_face_with_horns", false],
  "1f60a": ["Smiling face with smiling eyes", "smiling_face_with_smiling_eyes", false],
  "1f60e": ["Smiling face with sunglasses", "smiling_face_with_sunglasses", false],
  "1f972": ["Smiling face with tear", "smiling_face_with_tear", false],
  "1f60f": ["Smirking face", "smirking_face", false],
  "1f40c": ["Snail", "snail", false],
  "1f40d": ["Snake", "snake", false],
  "1f927": ["Sneezing face", "sneezing_face", false],
  "1f3c2": ["Snowboarder", "snowboarder", true],
  "2744": ["Snowflake", "snowflake", false],
  "2603": ["Snowman", "snowman", false],
  "26c4": ["Snowman without snow", "snowman_without_snow", false],
  "1f496": ["Sparkling heart", "sparkling_heart", false],
  "1f64a": ["Speak-no-evil monkey", "speak-no-evil_monkey", false],
  "1f5e3": ["Speaking head", "speaking_head", false],
  "1f6a4": ["Speedboat", "speedboat", false],
  "1f577": ["Spider", "spider", false],
  "1f578": ["Spider web", "spider_web", false],
  "1f5d3": ["Spiral calendar", "spiral_calendar", false],
  "1f41a": ["Spiral shell", "spiral_shell", false],
  "1f699": ["Sport utility vehicle", "sport_utility_vehicle", false],
  "1f433": ["Spouting whale", "spouting_whale", false],
  "1f991": ["Squid", "squid", false],
  "1f61d": ["Squinting face with tongue", "squinting_face_with_tongue", false],
  "2b50": ["Star", "star", false],
  "1f929": ["Star-struck", "star-struck", false],
  "23f1": ["Stopwatch", "stopwatch", false],
  "1f9d1-200d-1f393": ["Student", "student", true],
  "2600": ["Sun", "sun", false],
  "26c5": ["Sun behind cloud", "sun_behind_cloud", false],
  "1f325": ["Sun behind large cloud", "sun_behind_large_cloud", false],
  "1f326": ["Sun behind rain cloud", "sun_behind_rain_cloud", false],
  "1f324": ["Sun behind small cloud", "sun_behind_small_cloud", false],
  "1f31e": ["Sun with face", "sun_with_face", false],
  "1f69f": ["Suspension railway", "suspension_railway", false],
  "1f9a2": ["Swan", "swan", false],
  "1f996": ["T-rex", "t-rex", false],
  "1f695": ["Taxi", "taxi", false],
  "1f9d1-200d-1f3eb": ["Teacher", "teacher", true],
  "1f375": ["Teacup without handle", "teacup_without_handle", false],
  "1f9f8": ["Teddy bear", "teddy_bear", false],
  "1f4de": ["Telephone receiver", "telephone_receiver", false],
  "1f559": ["Ten oclock", "ten_oclock", false],
  "1f565": ["Ten-thirty", "ten-thirty", false],
  "1f914": ["Thinking face", "thinking_face", false],
  "1f552": ["Three oclock", "three_oclock", false],
  "1f55e": ["Three-thirty", "three-thirty", false],
  "1f44e": ["Thumbs down", "thumbs_down", true],
  "1f44d": ["Thumbs up", "thumbs_up", true],
  "1f405": ["Tiger", "tiger", false],
  "1f42f": ["Tiger face", "tiger_face", false],
  "23f2": ["Timer clock", "timer_clock", false],
  "1f62b": ["Tired face", "tired_face", false],
  "1f445": ["Tongue", "tongue", false],
  "1f9b7": ["Tooth", "tooth", false],
  "1f32a": ["Tornado", "tornado", false],
  "1f69c": ["Tractor", "tractor", false],
  "1f68b": ["Tram car", "tram_car", false],
  "1f3f3-200d-26a7": ["Transgender flag", "transgender_flag", false],
  "1f6a9": ["Triangular flag", "triangular_flag", false],
  "1f68e": ["Trolleybus", "trolleybus", false],
  "1f379": ["Tropical drink", "tropical_drink", false],
  "1f420": ["Tropical fish", "tropical_fish", false],
  "1f943": ["Tumbler glass", "tumbler_glass", false],
  "1f983": ["Turkey", "turkey", false],
  "1f422": ["Turtle", "turtle", false],
  "1f55b": ["Twelve oclock", "twelve_oclock", false],
  "1f567": ["Twelve-thirty", "twelve-thirty", false],
  "1f495": ["Two hearts", "two_hearts", false],
  "1f551": ["Two oclock", "two_oclock", false],
  "1f42b": ["Two-hump camel", "two-hump_camel", false],
  "1f55d": ["Two-thirty", "two-thirty", false],
  "2602": ["Umbrella", "umbrella", false],
  "2614": ["Umbrella with rain drops", "umbrella_with_rain_drops", false],
  "1f612": ["Unamused face", "unamused_face", false],
  "1f984": ["Unicorn", "unicorn", false],
  "1f643": ["Upside-down face", "upside-down_face", false],
  "270c": ["Victory hand", "victory_hand", true],
  "1f596": ["Vulcan salute", "vulcan_salute", true],
  "231a": ["Watch", "watch", false],
  "1f403": ["Water buffalo", "water_buffalo", false],
  "1f30a": ["Water wave", "water_wave", false],
  "1f44b": ["Waving hand", "waving_hand", true],
  "1f640": ["Weary cat", "weary_cat", false],
  "1f629": ["Weary face", "weary_face", false],
  "1f40b": ["Whale", "whale", false],
  "1f3f3": ["White flag", "white_flag", false],
  "1f90d": ["White heart", "white_heart", false],
  "1f940": ["Wilted flower", "wilted_flower", false],
  "1f32c": ["Wind face", "wind_face", false],
  "1fabd": ["Wing", "wing", false],
  "1f609": ["Winking face", "winking_face", false],
  "1f61c": ["Winking face with tongue", "winking_face_with_tongue", false],
  "1f43a": ["Wolf", "wolf", false],
  "1f469": ["Woman", "woman", true],
  "1f469-200d-1f680": ["Woman astronaut", "woman_astronaut", true],
  "1f469-200d-1f9b2": ["Woman bald", "woman_bald", true],
  "1f9d4-200d-2640": ["Woman beard", "woman_beard", true],
  "1f6b4-200d-2640": ["Woman biking", "woman_biking", true],
  "1f471-200d-2640": ["Woman blonde hair", "woman_blonde_hair", true],
  "26f9-200d-2640": ["Woman bouncing ball", "woman_bouncing_ball", true],
  "1f647-200d-2640": ["Woman bowing", "woman_bowing", true],
  "1f938-200d-2640": ["Woman cartwheeling", "woman_cartwheeling", true],
  "1f9d7-200d-2640": ["Woman climbing", "woman_climbing", true],
  "1f477-200d-2640": ["Woman construction worker", "woman_construction_worker", true],
  "1f469-200d-1f373": ["Woman cook", "woman_cook", true],
  "1f469-200d-1f9b1": ["Woman curly hair", "woman_curly_hair", true],
  "1f483": ["Woman dancing", "woman_dancing", true],
  "1f575-200d-2640": ["Woman detective", "woman_detective", true],
  "1f9dd-200d-2640": ["Woman elf", "woman_elf", true],
  "1f926-200d-2640": ["Woman facepalming", "woman_facepalming", true],
  "1f9da-200d-2640": ["Woman fairy", "woman_fairy", true],
  "1f469-200d-1f33e": ["Woman farmer", "woman_farmer", true],
  "1f469-200d-1f37c": ["Woman feeding baby", "woman_feeding_baby", true],
  "1f469-200d-1f692": ["Woman firefighter", "woman_firefighter", true],
  "1f64d-200d-2640": ["Woman frowning", "woman_frowning", true],
  "1f9de-200d-2640": ["Woman genie", "woman_genie", false],
  "1f645-200d-2640": ["Woman gesturing no", "woman_gesturing_no", true],
  "1f646-200d-2640": ["Woman gesturing ok", "woman_gesturing_ok", true],
  "1f487-200d-2640": ["Woman getting haircut", "woman_getting_haircut", true],
  "1f486-200d-2640": ["Woman getting massage", "woman_getting_massage", true],
  "1f3cc-200d-2640": ["Woman golfing", "woman_golfing", true],
  "1f482-200d-2640": ["Woman guard", "woman_guard", true],
  "1f469-200d-2695": ["Woman health worker", "woman_health_worker", true],
  "1f9d8-200d-2640": ["Woman in lotus position", "woman_in_lotus_position", true],
  "1f469-200d-1f9bc": ["Woman in motorized wheelchair", "woman_in_motorized_wheelchair", true],
  "1f469-200d-1f9bc-200d-27a1": ["Woman in motorized wheelchair facing right", "woman_in_motorized_wheelchair_facing_right", true],
  "1f9d6-200d-2640": ["Woman in steamy room", "woman_in_steamy_room", true],
  "1f935-200d-2640": ["Woman in tuxedo", "woman_in_tuxedo", true],
  "1f469-200d-2696": ["Woman judge", "woman_judge", true],
  "1f939-200d-2640": ["Woman juggling", "woman_juggling", true],
  "1f3cb-200d-2640": ["Woman lifting weights", "woman_lifting_weights", true],
  "1f9d9-200d-2640": ["Woman mage", "woman_mage", true],
  "1f469-200d-1f527": ["Woman mechanic", "woman_mechanic", true],
  "1f9dc-200d-2640": ["Woman merpeople", "woman_merpeople", true],
  "1f6b5-200d-2640": ["Woman mountain biking", "woman_mountain_biking", true],
  "1f469-200d-2708": ["Woman pilot", "woman_pilot", true],
  "1f93e-200d-2640": ["Woman playing handball", "woman_playing_handball", true],
  "1f93d-200d-2640": ["Woman playing water polo", "woman_playing_water_polo", true],
  "1f46e-200d-2640": ["Woman police officer", "woman_police_officer", true],
  "1f64e-200d-2640": ["Woman pouting", "woman_pouting", true],
  "1f64b-200d-2640": ["Woman raising hand", "woman_raising_hand", true],
  "1f469-200d-1f9b0": ["Woman red hair", "woman_red_hair", true],
  "1f6a3-200d-2640": ["Woman rowing boat", "woman_rowing_boat", true],
  "1f3c3-200d-2640": ["Woman running", "woman_running", true],
  "1f3c3-200d-2640-200d-27a1": ["Woman running facing right", "woman_running_facing_right", true],
  "1f469-200d-1f52c": ["Woman scientist", "woman_scientist", true],
  "1f937-200d-2640": ["Woman shrugging", "woman_shrugging", true],
  "1f9cd-200d-2640": ["Woman standing", "woman_standing", true],
  "1f469-200d-1f393": ["Woman student", "woman_student", true],
  "1f9b8-200d-2640": ["Woman superhero", "woman_superhero", true],
  "1f9b9-200d-2640": ["Woman supervillain", "woman_supervillain", true],
  "1f3c4-200d-2640": ["Woman surfing", "woman_surfing", true],
  "1f3ca-200d-2640": ["Woman swimming", "woman_swimming", true],
  "1f469-200d-1f3eb": ["Woman teacher", "woman_teacher", true],
  "1f481-200d-2640": ["Woman tipping hand", "woman_tipping_hand", true],
  "1f9db-200d-2640": ["Woman vampire", "woman_vampire", true],
  "1f6b6-200d-2640": ["Woman walking", "woman_walking", true],
  "1f6b6-200d-2640-200d-27a1": ["Woman walking facing right", "woman_walking_facing_right", true],
  "1f473-200d-2640": ["Woman wearing turban", "woman_wearing_turban", true],
  "1f469-200d-1f9b3": ["Woman white hair", "woman_white_hair", true],
  "1f46f-200d-2640": ["Woman with bunny ears", "woman_with_bunny_ears", true],
  "1f9d5": ["Woman with headscarf", "woman_with_headscarf", true],
  "1f470-200d-2640": ["Woman with veil", "woman_with_veil", true],
  "1f469-200d-1f9af": ["Woman with white cane", "woman_with_white_cane", true],
  "1f469-200d-1f9af-200d-27a1": ["Woman with white cane facing right", "woman_with_white_cane_facing_right", true],
  "1f93c-200d-2640": ["Woman wrestling", "woman_wrestling", true],
  "1f9df-200d-2640": ["Woman zombie", "woman_zombie", false],
  "1fab5": ["Wood", "wood", false],
  "1f974": ["Woozy face", "woozy_face", false],
  "1fab1": ["Worm", "worm", false],
  "1f61f": ["Worried face", "worried_face", false],
  "270d": ["Writing hand", "writing_hand", true],
  "1f971": ["Yawning face", "yawning_face", false],
  "1f49b": ["Yellow heart", "yellow_heart", false],
  "1f92a": ["Zany face", "zany_face", false],
  "1f993": ["Zebra", "zebra", false],
  "1f910": ["Zipper-mouth face", "zipper-mouth_face", false],
  "1f4a4": ["Zzz", "zzz", false],
};
